# Auto-generated Joint Inference Script
# Generated by: qsp_llm_workflows.julia_translator
#
# Targets:
#   - k_M1_pol_Watkins2007_IL12_TAM_reprogramming
#   - k_CCL2_sec_bcproxy_yoshimura2023
#   - k_C1_growth_pdac_tumor_doubling_jang2015
#   - q_Treg_T_in_PDAC_Tang2014
#   - k_CCL2_sec_Steube1999_proxy
#   - q_Treg_T_in_extravasation_PDAC
#   - k_apsc_death_melatoninPSC_Estaras2021
#   - q_CD8_T_in_yorty2007_sv11_brain_tumor
#   - k_psc_activation_apte1998
#   - k_Mac_rec_PDAC_M1_recruitment_Gu2023
#   - N_IL2_CD4_division_destiny_Gett1998
#   - k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015
#   - k_MDSC_rec_oscc_ccl2_oo2022
#   - n_CD8_clones_Meng2023_PDAC
#   - N_IL2_CD8_division_generations_castro2012
#   - k_Mac_rec_PDAC_TAM_recruitment_Chen2015
#   - k_apsc_death_RA_Xiao2015
#   - q_CD8_T_in_extravasation_boissonnas2007
#   - k_CCL2_sec_Fujita2010_PrSC
#   - k_M1_pol_repolarization_horhold2020
#   - k_C1_growth_pdac_human_vdt_ahn2017
#   - q_Treg_T_in_Tremblay2017_MRIcelltracking

using Turing
using DifferentialEquations
using Distributions
using StatsPlots
using Plots: mm
using Random

Random.seed!(42)

# ======================================================================
# OBSERVED DATA (Dict keyed by target_id)
# ======================================================================

const DATA = Dict(
    "k_M1_pol_Watkins2007_IL12_TAM_reprogramming" => (
        obs_median = [0.031249999999999997],
        obs_sigma = [0.5605164738102602],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("t_reprogram_max_90min" => 90, "assumed_half_life_fraction" => 0.5, "assumed_fold_uncertainty" => 3),
    ),
    "k_CCL2_sec_bcproxy_yoshimura2023" => (
        obs_median = [30.0],
        obs_sigma = [0.47238072707743883],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("MDA_MB231_CCL2_mass_48h" => 30, "MDA_MB231_time_interval_48h" => 48, "MDA_MB231_cell_count" => 1000000, "CCL2_molecular_weight" => 11024.87, "assumed_cv" => 0.5),
    ),
    "k_C1_growth_pdac_tumor_doubling_jang2015" => (
        obs_median = [151.7],
        obs_sigma = [0.9436019284872316],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("jang_vdT_mean" => 151.7, "jang_vdT_min" => 18.3, "jang_vdT_max" => 417.8, "jang_n_patients" => 22),
    ),
    "q_Treg_T_in_PDAC_Tang2014" => (
        obs_median = [3.092962641181581],
        obs_sigma = [0.30822138330525917],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("PDAC_TIL_Treg_fraction_mean" => 0.178, "PDAC_TIL_Treg_fraction_sem" => 0.007075, "PBMC_Treg_fraction_mean" => 0.05755, "PBMC_Treg_fraction_sem" => 0.00145, "Treg_doubling_time_mean" => 8, "n_patients" => 45),
    ),
    "k_CCL2_sec_Steube1999_proxy" => (
        obs_median = [784.8566748139433],
        obs_sigma = [0.2952685685436335],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("mcp1_constitutive_min_pg_per_ml_per_millioncells" => 440, "mcp1_constitutive_max_pg_per_ml_per_millioncells" => 1400, "mcp1_stimulated_max_ng_per_ml_per_millioncells_24h" => 80),
    ),
    "q_Treg_T_in_extravasation_PDAC" => (
        obs_median = [0.6869627851140456],
        obs_sigma = [0.3123785017232525],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("treg_density_tumor_panc_120_per_mm2" => 120, "treg_density_adjacent_pancreas_80_per_mm2" => 80, "treg_transmigration_conventional_invitro_cells" => 3332, "treg_transmigration_treg_invitro_cells" => 4976, "cd34_migration_fraction_4h" => 0.46, "migration_time_4h_hr" => 4, "assumed_cv_migration_fraction" => 0.2, "assumed_cv_transmigration_ratio" => 0.25, "max_migration_fraction" => 0.99),
    ),
    "k_apsc_death_melatoninPSC_Estaras2021" => (
        obs_median = [0.8677],
        obs_sigma = [0.019918584287042088],
        sd_uncertain = [false],
        likelihood = ["normal"],
        t_span = (0.0, 2.0),
        t_eval = [2.0],
        y0 = [1.0],
    ),
    "q_CD8_T_in_yorty2007_sv11_brain_tumor" => (
        obs_median = [5.916079783099616],
        obs_sigma = [0.08583475424010535],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("t_peak_immune_lower" => 5, "t_peak_immune_upper" => 7, "reference_tumor_volume" => 1),
    ),
    "k_psc_activation_apte1998" => (
        obs_median = [48.0],
        obs_sigma = [0.24622067706923975],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("psc_activation_time_48h" => 48, "assumed_cv" => 0.25),
    ),
    "k_Mac_rec_PDAC_M1_recruitment_Gu2023" => (
        obs_median = [11.6],
        obs_sigma = [0.33718261224038765],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("M1_per_HPF_primary_PDAC" => 11.6, "section_thickness_histology" => 4, "HPF_area_400x_microscope" => 0.196, "macrophage_half_life_min" => 4, "macrophage_half_life_max" => 15),
    ),
    "N_IL2_CD4_division_destiny_Gett1998" => (
        obs_median = [8.0],
        obs_sigma = [2.0],
        sd_uncertain = [false],
        likelihood = ["normal"],
        inputs = Dict("max_divisions_cd4_antiCD3_IL2_IL4" => 8, "assumed_cv" => 0.25),
    ),
    "k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015" => (
        obs_median = [8.1],
        obs_sigma = [0.29008531439248997],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("B16_MDSC_fraction_control" => 8.1, "B16_MDSC_fraction_control_sd" => 2.4, "tumor_cell_density" => 1000000000, "MDSC_half_life" => 1.5),
    ),
    "k_MDSC_rec_oscc_ccl2_oo2022" => (
        obs_median = [610.0],
        obs_sigma = [1.2109109281940988],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("bm_cells_migrated_PDS1_9h_per_field" => 610, "migration_time_9h" => 9, "lower_chamber_volume" => 0.75, "imaging_volume_per_field" => 0.01, "bm_cells_initial_upper_chamber" => 500000, "assumed_cv_migrated" => 0.3, "imaging_volume_uncertainty_fold" => 10),
    ),
    "n_CD8_clones_Meng2023_PDAC" => (
        obs_median = [93.0],
        obs_sigma = [0.10341803090732268],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("total_TR_clonotypes_Meng2023" => 93, "n_PDAC_tumors_Meng2023" => 9),
    ),
    "N_IL2_CD8_division_generations_castro2012" => (
        obs_median = [40.0, 70.0],
        obs_sigma = [15.0, 34.0],
        sd_uncertain = [false, false],
        likelihood = ["normal", "normal"],
        inputs = Dict("fold_increase_memory_day10" => 40, "fold_increase_memory_day30" => 70, "fold_increase_memory_day10_sem" => 15, "fold_increase_memory_day30_sem" => 34),
    ),
    "k_Mac_rec_PDAC_TAM_recruitment_Chen2015" => (
        obs_median = [100562587.9043601],
        obs_sigma = [0.6600542314828027],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("cd68_peri_median_per_hpf" => 71.5, "cd68_peri_range_low_per_hpf" => 13, "cd68_peri_range_high_per_hpf" => 198, "section_thickness_um" => 3, "hpf_area_mm2" => 0.237, "macrophage_res_time_days" => 30, "H_CCL2_PD" => 1),
    ),
    "k_apsc_death_RA_Xiao2015" => (
        obs_median = [5.0],
        obs_sigma = [1.0],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("half_life_apsc" => 5, "assumed_sigma_log" => 1),
    ),
    "q_CD8_T_in_extravasation_boissonnas2007" => (
        obs_median = [327.0],
        obs_sigma = [0.28215854750622943],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("OT1_injected" => 10000000, "EG7_tumor_volume_min" => 500, "EG7_tumor_volume_max" => 1000, "OT1_density_day6" => 327, "OT1_density_day6_sd" => 50, "section_thickness_um" => 5, "CD8_eff_half_life" => 41, "CD8_eff_half_life_sd" => 10),
    ),
    "k_CCL2_sec_Fujita2010_PrSC" => (
        obs_median = [1888.0],
        obs_sigma = [0.325408570007528],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("CCL2_prsc_unstim_mean" => 1888, "CCL2_prsc_unstim_sd" => 631, "n_cells_prsc" => 100000, "incubation_time_hours" => 48, "V_medium_ml" => 1),
    ),
    "k_M1_pol_repolarization_horhold2020" => (
        obs_median = [1.4142135623730951],
        obs_sigma = [0.17682326034692483],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("m2_to_m1_repol_time_low" => 24, "m2_to_m1_repol_time_high" => 48),
    ),
    "k_C1_growth_pdac_human_vdt_ahn2017" => (
        obs_median = [132.3],
        obs_sigma = [0.8316462380958335],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("vdtime_mean" => 132.3, "vdtime_sd" => 132.1),
    ),
    "q_Treg_T_in_Tremblay2017_MRIcelltracking" => (
        obs_median = [24.0],
        obs_sigma = [0.5605164738102602],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("t_vis_Treg" => 24, "V_T_ref" => 1, "assumed_fold_uncertainty" => 3),
    )
)


# ======================================================================
# ODE SUBMODELS
# ======================================================================

# ======================================================================
# SIMULATION FUNCTIONS
# ======================================================================
function compute_k_M1_pol_Watkins2007_IL12_TAM_reprogramming(params, inputs)
    k = params["k_M1_pol"]
    t_half_days = log(2) / k
    return t_half_days  # days
end

function compute_k_CCL2_sec_bcproxy_yoshimura2023(params, inputs)
    k = params["k_CCL2_sec"]
    cells = inputs["MDA_MB231_cell_count"]
    time_days = inputs["MDA_MB231_time_interval_48h"] / 24.0
    mw = inputs["CCL2_molecular_weight"]
    nmol = k * cells * time_days
    mass_g = nmol * 1e-9 * mw
    mass_ng = mass_g * 1e9
    return mass_ng  # nanograms
end

function compute_k_C1_growth_pdac_tumor_doubling_jang2015(params, inputs)
    k = params["k_C1_growth"]  # 1/day
    return log(2) / k  # in days
end

function compute_q_Treg_T_in_PDAC_Tang2014(params, inputs)
    q = params["q_Treg_T_in"]
    t_doubling = inputs["Treg_doubling_time_mean"]
    k_per_day = log(2) / t_doubling
    k_per_min = k_per_day / (24.0 * 60.0)
    V_ref = 1.0
    ratio = q * V_ref / k_per_min
    return ratio
end

function compute_k_CCL2_sec_Steube1999_proxy(params, inputs)
    k = params["k_CCL2_sec"]
    MW = 8700.0
    mcp1_pg = k * 1e6 * 1.0 / (1e-12 / MW * 1e9)
    return mcp1_pg  # pg/mL per 1e6 cells
end

function compute_q_Treg_T_in_extravasation_PDAC(params, inputs)
    q = params["q_Treg_T_in"]
    tau_hr = inputs["migration_time_4h_hr"]
    tau_min = tau_hr * 60.0
    V_T_ref = 1.0
    k_in = q * V_T_ref
    f_treg = 1.0 - exp(-k_in * tau_min)
    return f_treg
end


# Analytical solution for first-order decay: du/dt = -k*u => u(t) = u₀ * exp(-k*t)
function simulate_k_apsc_death_melatoninPSC_Estaras2021(k_apsc_death)
    d = DATA["k_apsc_death_melatoninPSC_Estaras2021"]
    t_final = d.t_span[2]
    y0 = d.y0[1]
    return y0 * exp(-k_apsc_death * t_final)
end

function compute_q_CD8_T_in_yorty2007_sv11_brain_tumor(params, inputs)
    q = params["q_CD8_T_in"]
    V_ref = inputs["reference_tumor_volume"]
    k_in_per_min = q * V_ref
    t_peak_min = 3.0 / k_in_per_min
    t_peak_days = t_peak_min / (24.0 * 60.0)
    return t_peak_days  # days
end

function compute_k_psc_activation_apte1998(params, inputs)
    k = params["k_psc_activation"]
    t_days = 1.0 / k
    t_hours = t_days * 24.0
    return t_hours  # hours
end

function compute_k_Mac_rec_PDAC_M1_recruitment_Gu2023(params, inputs)
    k_rec = params["k_Mac_rec"]
    A = inputs["HPF_area_400x_microscope"]
    thickness = inputs["section_thickness_histology"]
    t_min = inputs["macrophage_half_life_min"]
    t_max = inputs["macrophage_half_life_max"]
    t_half = (t_min + t_max) / 2.0
    k_death = log(2) / t_half
    V_mm3 = A * thickness
    V_mL = V_mm3 / 1000.0
    density = k_rec / k_death
    M1_per_HPF = density * V_mL
    return M1_per_HPF  # cells per HPF
end

function compute_N_IL2_CD4_division_destiny_Gett1998(params, inputs)
    N = params["N_IL2_CD4"]
    return N
end

function compute_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015(params, inputs)
    k_rec = params["k_MDSC_rec"]
    cell_density = inputs["tumor_cell_density"]
    half_life = inputs["MDSC_half_life"]
    k_death = log(2) / half_life
    frac = k_rec / (k_death * cell_density) * 100.0
    return frac  # percent
end

function compute_k_MDSC_rec_oscc_ccl2_oo2022(params, inputs)
    k_rec = params["k_MDSC_rec"]
    V_eff = inputs["imaging_volume_per_field"]
    t_hours = inputs["migration_time_9h"]
    t_days = t_hours / 24.0
    migrated = k_rec * V_eff * t_days
    return migrated  # cells
end

function compute_n_CD8_clones_Meng2023_PDAC(params, inputs)
    n_clones = params["n_CD8_clones"]
    n_tumors = inputs["n_PDAC_tumors_Meng2023"]
    total_tr = n_clones * n_tumors
    return total_tr
end

function compute_N_IL2_CD8_division_generations_castro2012(params, inputs)
    N = params["N_IL2_CD8"]
    fold_increase = 2.0 ^ N
    return fold_increase
end

function compute_k_Mac_rec_PDAC_TAM_recruitment_Chen2015(params, inputs)
    # Numeric implementation; units are handled externally in the inference engine
    k_rec = params["k_Mac_rec"]
    tau = inputs["macrophage_res_time_days"]
    H = inputs["H_CCL2_PD"]  # dimensionless
    # Effective loss rate 1/day
    k_loss = log(2.0) / tau
    rho = (k_rec / k_loss) * H
    return rho
end

function compute_k_apsc_death_RA_Xiao2015(params, inputs)
    k = params["k_apsc_death"]
    t_half = log(2) / k
    return t_half  # days
end

function compute_q_CD8_T_in_extravasation_boissonnas2007(params, inputs)
    q = params["q_CD8_T_in"]
    CD8_C = inputs["OT1_injected"]
    t_half_h = inputs["CD8_eff_half_life"]
    k_death = log(2) / (t_half_h * 60.0)
    thickness_mm = inputs["section_thickness_um"] / 1000.0
    rho = q * CD8_C / k_death / 1000.0
    d_2d = rho * thickness_mm
    return d_2d  # cells/mm^2
end

function compute_k_CCL2_sec_Fujita2010_PrSC(params, inputs)
    k = params["k_CCL2_sec"]
    N_cells = inputs["n_cells_prsc"]
    t_h = inputs["incubation_time_hours"]
    V_ml = inputs["V_medium_ml"]
    MW = 8.7e3
    days = t_h / 24.0
    nmol = k * N_cells * days
    mass_g = nmol * 1e-9 * MW
    mass_pg = mass_g * 1e12
    conc = mass_pg / V_ml
    return conc  # pg/mL
end

function compute_k_M1_pol_repolarization_horhold2020(params, inputs)
    k = params["k_M1_pol"]
    t_half_days = log(2) / k
    return t_half_days  # days
end

function compute_k_C1_growth_pdac_human_vdt_ahn2017(params, inputs)
    k = params["k_C1_growth"]
    vdt = log(2) / k
    return vdt  # days
end

function compute_q_Treg_T_in_Tremblay2017_MRIcelltracking(params, inputs)
    q = params["q_Treg_T_in"]
    V_ref = inputs["V_T_ref"]
    k_extrav_per_min = q * V_ref
    t_half_min = log(2) / k_extrav_per_min
    t_half_h = t_half_min / 60.0
    return t_half_h  # hours
end


# ======================================================================
# JOINT TURING MODEL
# ======================================================================
@model function joint_calibration(data)
    # =========================================
    # PRIORS (shared across targets)
    # =========================================
    k_M1_pol ~ LogNormal(3.0, 1.7)  # Used by: k_M1_pol_Watkins2007_IL12_TAM_reprogramming, k_M1_pol_repolarization_horhold2020
    k_CCL2_sec ~ LogNormal(-20.64, 2.5)  # Used by: k_CCL2_sec_bcproxy_yoshimura2023, k_CCL2_sec_Steube1999_proxy, k_CCL2_sec_Fujita2010_PrSC
    k_C1_growth ~ LogNormal(-5.0, 1.0)  # Used by: k_C1_growth_pdac_tumor_doubling_jang2015, k_C1_growth_pdac_human_vdt_ahn2017
    q_Treg_T_in ~ LogNormal(-7.64, 1.7)  # Used by: q_Treg_T_in_PDAC_Tang2014, q_Treg_T_in_extravasation_PDAC, q_Treg_T_in_Tremblay2017_MRIcelltracking
    k_apsc_death ~ LogNormal(-2.65, 1.7)  # Used by: k_apsc_death_melatoninPSC_Estaras2021, k_apsc_death_RA_Xiao2015
    q_CD8_T_in ~ LogNormal(-8.0, 3.4)  # Used by: q_CD8_T_in_yorty2007_sv11_brain_tumor, q_CD8_T_in_extravasation_boissonnas2007
    k_psc_activation ~ LogNormal(-0.693, 1.0)  # Used by: k_psc_activation_apte1998
    k_Mac_rec ~ LogNormal(14.66, 1.0)  # Used by: k_Mac_rec_PDAC_M1_recruitment_Gu2023, k_Mac_rec_PDAC_TAM_recruitment_Chen2015
    N_IL2_CD4 ~ Normal(8.0, 2.0)  # Used by: N_IL2_CD4_division_destiny_Gett1998
    k_MDSC_rec ~ LogNormal(17.44, 2.5)  # Used by: k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015, k_MDSC_rec_oscc_ccl2_oo2022
    n_CD8_clones ~ LogNormal(2.3, 1.0)  # Used by: n_CD8_clones_Meng2023_PDAC
    N_IL2_CD8 ~ Normal(5.0, 2.0)  # Used by: N_IL2_CD8_division_generations_castro2012

    # =========================================
    # LIKELIHOODS
    # =========================================

    # k_M1_pol_Watkins2007_IL12_TAM_reprogramming
    params_k_M1_pol_Watkins2007_IL12_TAM_reprogramming = Dict("k_M1_pol" => k_M1_pol)
    inputs_k_M1_pol_Watkins2007_IL12_TAM_reprogramming = data["k_M1_pol_Watkins2007_IL12_TAM_reprogramming"].inputs
    pred_k_M1_pol_Watkins2007_IL12_TAM_reprogramming = compute_k_M1_pol_Watkins2007_IL12_TAM_reprogramming(params_k_M1_pol_Watkins2007_IL12_TAM_reprogramming, inputs_k_M1_pol_Watkins2007_IL12_TAM_reprogramming)
    data["k_M1_pol_Watkins2007_IL12_TAM_reprogramming"].obs_median[1] ~ LogNormal(log(pred_k_M1_pol_Watkins2007_IL12_TAM_reprogramming), data["k_M1_pol_Watkins2007_IL12_TAM_reprogramming"].obs_sigma[1])

    # k_CCL2_sec_bcproxy_yoshimura2023
    params_k_CCL2_sec_bcproxy_yoshimura2023 = Dict("k_CCL2_sec" => k_CCL2_sec)
    inputs_k_CCL2_sec_bcproxy_yoshimura2023 = data["k_CCL2_sec_bcproxy_yoshimura2023"].inputs
    pred_k_CCL2_sec_bcproxy_yoshimura2023 = compute_k_CCL2_sec_bcproxy_yoshimura2023(params_k_CCL2_sec_bcproxy_yoshimura2023, inputs_k_CCL2_sec_bcproxy_yoshimura2023)
    data["k_CCL2_sec_bcproxy_yoshimura2023"].obs_median[1] ~ LogNormal(log(pred_k_CCL2_sec_bcproxy_yoshimura2023), data["k_CCL2_sec_bcproxy_yoshimura2023"].obs_sigma[1])

    # k_C1_growth_pdac_tumor_doubling_jang2015
    params_k_C1_growth_pdac_tumor_doubling_jang2015 = Dict("k_C1_growth" => k_C1_growth)
    inputs_k_C1_growth_pdac_tumor_doubling_jang2015 = data["k_C1_growth_pdac_tumor_doubling_jang2015"].inputs
    pred_k_C1_growth_pdac_tumor_doubling_jang2015 = compute_k_C1_growth_pdac_tumor_doubling_jang2015(params_k_C1_growth_pdac_tumor_doubling_jang2015, inputs_k_C1_growth_pdac_tumor_doubling_jang2015)
    data["k_C1_growth_pdac_tumor_doubling_jang2015"].obs_median[1] ~ LogNormal(log(pred_k_C1_growth_pdac_tumor_doubling_jang2015), data["k_C1_growth_pdac_tumor_doubling_jang2015"].obs_sigma[1])

    # q_Treg_T_in_PDAC_Tang2014
    params_q_Treg_T_in_PDAC_Tang2014 = Dict("q_Treg_T_in" => q_Treg_T_in)
    inputs_q_Treg_T_in_PDAC_Tang2014 = data["q_Treg_T_in_PDAC_Tang2014"].inputs
    pred_q_Treg_T_in_PDAC_Tang2014 = compute_q_Treg_T_in_PDAC_Tang2014(params_q_Treg_T_in_PDAC_Tang2014, inputs_q_Treg_T_in_PDAC_Tang2014)
    data["q_Treg_T_in_PDAC_Tang2014"].obs_median[1] ~ LogNormal(log(pred_q_Treg_T_in_PDAC_Tang2014), data["q_Treg_T_in_PDAC_Tang2014"].obs_sigma[1])

    # k_CCL2_sec_Steube1999_proxy
    params_k_CCL2_sec_Steube1999_proxy = Dict("k_CCL2_sec" => k_CCL2_sec)
    inputs_k_CCL2_sec_Steube1999_proxy = data["k_CCL2_sec_Steube1999_proxy"].inputs
    pred_k_CCL2_sec_Steube1999_proxy = compute_k_CCL2_sec_Steube1999_proxy(params_k_CCL2_sec_Steube1999_proxy, inputs_k_CCL2_sec_Steube1999_proxy)
    data["k_CCL2_sec_Steube1999_proxy"].obs_median[1] ~ LogNormal(log(pred_k_CCL2_sec_Steube1999_proxy), data["k_CCL2_sec_Steube1999_proxy"].obs_sigma[1])

    # q_Treg_T_in_extravasation_PDAC
    params_q_Treg_T_in_extravasation_PDAC = Dict("q_Treg_T_in" => q_Treg_T_in)
    inputs_q_Treg_T_in_extravasation_PDAC = data["q_Treg_T_in_extravasation_PDAC"].inputs
    pred_q_Treg_T_in_extravasation_PDAC = compute_q_Treg_T_in_extravasation_PDAC(params_q_Treg_T_in_extravasation_PDAC, inputs_q_Treg_T_in_extravasation_PDAC)
    data["q_Treg_T_in_extravasation_PDAC"].obs_median[1] ~ LogNormal(log(pred_q_Treg_T_in_extravasation_PDAC), data["q_Treg_T_in_extravasation_PDAC"].obs_sigma[1])

    # k_apsc_death_melatoninPSC_Estaras2021
    pred_k_apsc_death_melatoninPSC_Estaras2021 = simulate_k_apsc_death_melatoninPSC_Estaras2021(k_apsc_death)
    data["k_apsc_death_melatoninPSC_Estaras2021"].obs_median[1] ~ Normal(pred_k_apsc_death_melatoninPSC_Estaras2021, data["k_apsc_death_melatoninPSC_Estaras2021"].obs_sigma[1])

    # q_CD8_T_in_yorty2007_sv11_brain_tumor
    params_q_CD8_T_in_yorty2007_sv11_brain_tumor = Dict("q_CD8_T_in" => q_CD8_T_in)
    inputs_q_CD8_T_in_yorty2007_sv11_brain_tumor = data["q_CD8_T_in_yorty2007_sv11_brain_tumor"].inputs
    pred_q_CD8_T_in_yorty2007_sv11_brain_tumor = compute_q_CD8_T_in_yorty2007_sv11_brain_tumor(params_q_CD8_T_in_yorty2007_sv11_brain_tumor, inputs_q_CD8_T_in_yorty2007_sv11_brain_tumor)
    data["q_CD8_T_in_yorty2007_sv11_brain_tumor"].obs_median[1] ~ LogNormal(log(pred_q_CD8_T_in_yorty2007_sv11_brain_tumor), data["q_CD8_T_in_yorty2007_sv11_brain_tumor"].obs_sigma[1])

    # k_psc_activation_apte1998
    params_k_psc_activation_apte1998 = Dict("k_psc_activation" => k_psc_activation)
    inputs_k_psc_activation_apte1998 = data["k_psc_activation_apte1998"].inputs
    pred_k_psc_activation_apte1998 = compute_k_psc_activation_apte1998(params_k_psc_activation_apte1998, inputs_k_psc_activation_apte1998)
    data["k_psc_activation_apte1998"].obs_median[1] ~ LogNormal(log(pred_k_psc_activation_apte1998), data["k_psc_activation_apte1998"].obs_sigma[1])

    # k_Mac_rec_PDAC_M1_recruitment_Gu2023
    params_k_Mac_rec_PDAC_M1_recruitment_Gu2023 = Dict("k_Mac_rec" => k_Mac_rec)
    inputs_k_Mac_rec_PDAC_M1_recruitment_Gu2023 = data["k_Mac_rec_PDAC_M1_recruitment_Gu2023"].inputs
    pred_k_Mac_rec_PDAC_M1_recruitment_Gu2023 = compute_k_Mac_rec_PDAC_M1_recruitment_Gu2023(params_k_Mac_rec_PDAC_M1_recruitment_Gu2023, inputs_k_Mac_rec_PDAC_M1_recruitment_Gu2023)
    data["k_Mac_rec_PDAC_M1_recruitment_Gu2023"].obs_median[1] ~ LogNormal(log(pred_k_Mac_rec_PDAC_M1_recruitment_Gu2023), data["k_Mac_rec_PDAC_M1_recruitment_Gu2023"].obs_sigma[1])

    # N_IL2_CD4_division_destiny_Gett1998
    params_N_IL2_CD4_division_destiny_Gett1998 = Dict("N_IL2_CD4" => N_IL2_CD4)
    inputs_N_IL2_CD4_division_destiny_Gett1998 = data["N_IL2_CD4_division_destiny_Gett1998"].inputs
    pred_N_IL2_CD4_division_destiny_Gett1998 = compute_N_IL2_CD4_division_destiny_Gett1998(params_N_IL2_CD4_division_destiny_Gett1998, inputs_N_IL2_CD4_division_destiny_Gett1998)
    data["N_IL2_CD4_division_destiny_Gett1998"].obs_median[1] ~ Normal(pred_N_IL2_CD4_division_destiny_Gett1998, data["N_IL2_CD4_division_destiny_Gett1998"].obs_sigma[1])

    # k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015
    params_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015 = Dict("k_MDSC_rec" => k_MDSC_rec)
    inputs_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015 = data["k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015"].inputs
    pred_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015 = compute_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015(params_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015, inputs_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015)
    data["k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015"].obs_median[1] ~ LogNormal(log(pred_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015), data["k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015"].obs_sigma[1])

    # k_MDSC_rec_oscc_ccl2_oo2022
    params_k_MDSC_rec_oscc_ccl2_oo2022 = Dict("k_MDSC_rec" => k_MDSC_rec)
    inputs_k_MDSC_rec_oscc_ccl2_oo2022 = data["k_MDSC_rec_oscc_ccl2_oo2022"].inputs
    pred_k_MDSC_rec_oscc_ccl2_oo2022 = compute_k_MDSC_rec_oscc_ccl2_oo2022(params_k_MDSC_rec_oscc_ccl2_oo2022, inputs_k_MDSC_rec_oscc_ccl2_oo2022)
    data["k_MDSC_rec_oscc_ccl2_oo2022"].obs_median[1] ~ LogNormal(log(pred_k_MDSC_rec_oscc_ccl2_oo2022), data["k_MDSC_rec_oscc_ccl2_oo2022"].obs_sigma[1])

    # n_CD8_clones_Meng2023_PDAC
    params_n_CD8_clones_Meng2023_PDAC = Dict("n_CD8_clones" => n_CD8_clones)
    inputs_n_CD8_clones_Meng2023_PDAC = data["n_CD8_clones_Meng2023_PDAC"].inputs
    pred_n_CD8_clones_Meng2023_PDAC = compute_n_CD8_clones_Meng2023_PDAC(params_n_CD8_clones_Meng2023_PDAC, inputs_n_CD8_clones_Meng2023_PDAC)
    data["n_CD8_clones_Meng2023_PDAC"].obs_median[1] ~ LogNormal(log(pred_n_CD8_clones_Meng2023_PDAC), data["n_CD8_clones_Meng2023_PDAC"].obs_sigma[1])

    # N_IL2_CD8_division_generations_castro2012
    params_N_IL2_CD8_division_generations_castro2012 = Dict("N_IL2_CD8" => N_IL2_CD8)
    inputs_N_IL2_CD8_division_generations_castro2012 = data["N_IL2_CD8_division_generations_castro2012"].inputs
    pred_N_IL2_CD8_division_generations_castro2012 = compute_N_IL2_CD8_division_generations_castro2012(params_N_IL2_CD8_division_generations_castro2012, inputs_N_IL2_CD8_division_generations_castro2012)
    data["N_IL2_CD8_division_generations_castro2012"].obs_median[1] ~ Normal(pred_N_IL2_CD8_division_generations_castro2012, data["N_IL2_CD8_division_generations_castro2012"].obs_sigma[1])
    data["N_IL2_CD8_division_generations_castro2012"].obs_median[2] ~ Normal(pred_N_IL2_CD8_division_generations_castro2012, data["N_IL2_CD8_division_generations_castro2012"].obs_sigma[2])

    # k_Mac_rec_PDAC_TAM_recruitment_Chen2015
    params_k_Mac_rec_PDAC_TAM_recruitment_Chen2015 = Dict("k_Mac_rec" => k_Mac_rec)
    inputs_k_Mac_rec_PDAC_TAM_recruitment_Chen2015 = data["k_Mac_rec_PDAC_TAM_recruitment_Chen2015"].inputs
    pred_k_Mac_rec_PDAC_TAM_recruitment_Chen2015 = compute_k_Mac_rec_PDAC_TAM_recruitment_Chen2015(params_k_Mac_rec_PDAC_TAM_recruitment_Chen2015, inputs_k_Mac_rec_PDAC_TAM_recruitment_Chen2015)
    data["k_Mac_rec_PDAC_TAM_recruitment_Chen2015"].obs_median[1] ~ LogNormal(log(pred_k_Mac_rec_PDAC_TAM_recruitment_Chen2015), data["k_Mac_rec_PDAC_TAM_recruitment_Chen2015"].obs_sigma[1])

    # k_apsc_death_RA_Xiao2015
    params_k_apsc_death_RA_Xiao2015 = Dict("k_apsc_death" => k_apsc_death)
    inputs_k_apsc_death_RA_Xiao2015 = data["k_apsc_death_RA_Xiao2015"].inputs
    pred_k_apsc_death_RA_Xiao2015 = compute_k_apsc_death_RA_Xiao2015(params_k_apsc_death_RA_Xiao2015, inputs_k_apsc_death_RA_Xiao2015)
    data["k_apsc_death_RA_Xiao2015"].obs_median[1] ~ LogNormal(log(pred_k_apsc_death_RA_Xiao2015), data["k_apsc_death_RA_Xiao2015"].obs_sigma[1])

    # q_CD8_T_in_extravasation_boissonnas2007
    params_q_CD8_T_in_extravasation_boissonnas2007 = Dict("q_CD8_T_in" => q_CD8_T_in)
    inputs_q_CD8_T_in_extravasation_boissonnas2007 = data["q_CD8_T_in_extravasation_boissonnas2007"].inputs
    pred_q_CD8_T_in_extravasation_boissonnas2007 = compute_q_CD8_T_in_extravasation_boissonnas2007(params_q_CD8_T_in_extravasation_boissonnas2007, inputs_q_CD8_T_in_extravasation_boissonnas2007)
    data["q_CD8_T_in_extravasation_boissonnas2007"].obs_median[1] ~ LogNormal(log(pred_q_CD8_T_in_extravasation_boissonnas2007), data["q_CD8_T_in_extravasation_boissonnas2007"].obs_sigma[1])

    # k_CCL2_sec_Fujita2010_PrSC
    params_k_CCL2_sec_Fujita2010_PrSC = Dict("k_CCL2_sec" => k_CCL2_sec)
    inputs_k_CCL2_sec_Fujita2010_PrSC = data["k_CCL2_sec_Fujita2010_PrSC"].inputs
    pred_k_CCL2_sec_Fujita2010_PrSC = compute_k_CCL2_sec_Fujita2010_PrSC(params_k_CCL2_sec_Fujita2010_PrSC, inputs_k_CCL2_sec_Fujita2010_PrSC)
    data["k_CCL2_sec_Fujita2010_PrSC"].obs_median[1] ~ LogNormal(log(pred_k_CCL2_sec_Fujita2010_PrSC), data["k_CCL2_sec_Fujita2010_PrSC"].obs_sigma[1])

    # k_M1_pol_repolarization_horhold2020
    params_k_M1_pol_repolarization_horhold2020 = Dict("k_M1_pol" => k_M1_pol)
    inputs_k_M1_pol_repolarization_horhold2020 = data["k_M1_pol_repolarization_horhold2020"].inputs
    pred_k_M1_pol_repolarization_horhold2020 = compute_k_M1_pol_repolarization_horhold2020(params_k_M1_pol_repolarization_horhold2020, inputs_k_M1_pol_repolarization_horhold2020)
    data["k_M1_pol_repolarization_horhold2020"].obs_median[1] ~ LogNormal(log(pred_k_M1_pol_repolarization_horhold2020), data["k_M1_pol_repolarization_horhold2020"].obs_sigma[1])

    # k_C1_growth_pdac_human_vdt_ahn2017
    params_k_C1_growth_pdac_human_vdt_ahn2017 = Dict("k_C1_growth" => k_C1_growth)
    inputs_k_C1_growth_pdac_human_vdt_ahn2017 = data["k_C1_growth_pdac_human_vdt_ahn2017"].inputs
    pred_k_C1_growth_pdac_human_vdt_ahn2017 = compute_k_C1_growth_pdac_human_vdt_ahn2017(params_k_C1_growth_pdac_human_vdt_ahn2017, inputs_k_C1_growth_pdac_human_vdt_ahn2017)
    data["k_C1_growth_pdac_human_vdt_ahn2017"].obs_median[1] ~ LogNormal(log(pred_k_C1_growth_pdac_human_vdt_ahn2017), data["k_C1_growth_pdac_human_vdt_ahn2017"].obs_sigma[1])

    # q_Treg_T_in_Tremblay2017_MRIcelltracking
    params_q_Treg_T_in_Tremblay2017_MRIcelltracking = Dict("q_Treg_T_in" => q_Treg_T_in)
    inputs_q_Treg_T_in_Tremblay2017_MRIcelltracking = data["q_Treg_T_in_Tremblay2017_MRIcelltracking"].inputs
    pred_q_Treg_T_in_Tremblay2017_MRIcelltracking = compute_q_Treg_T_in_Tremblay2017_MRIcelltracking(params_q_Treg_T_in_Tremblay2017_MRIcelltracking, inputs_q_Treg_T_in_Tremblay2017_MRIcelltracking)
    data["q_Treg_T_in_Tremblay2017_MRIcelltracking"].obs_median[1] ~ LogNormal(log(pred_q_Treg_T_in_Tremblay2017_MRIcelltracking), data["q_Treg_T_in_Tremblay2017_MRIcelltracking"].obs_sigma[1])

    return (k_M1_pol=k_M1_pol, k_CCL2_sec=k_CCL2_sec, k_C1_growth=k_C1_growth, q_Treg_T_in=q_Treg_T_in, k_apsc_death=k_apsc_death, q_CD8_T_in=q_CD8_T_in, k_psc_activation=k_psc_activation, k_Mac_rec=k_Mac_rec, N_IL2_CD4=N_IL2_CD4, k_MDSC_rec=k_MDSC_rec, n_CD8_clones=n_CD8_clones, N_IL2_CD8=N_IL2_CD8)
end

# ======================================================================
# RUN INFERENCE
# ======================================================================

model = joint_calibration(DATA)

println("=" ^ 60)
println("JOINT BAYESIAN CALIBRATION")
println("=" ^ 60)
println("\nTargets:")
println("  - k_M1_pol_Watkins2007_IL12_TAM_reprogramming")
println("  - k_CCL2_sec_bcproxy_yoshimura2023")
println("  - k_C1_growth_pdac_tumor_doubling_jang2015")
println("  - q_Treg_T_in_PDAC_Tang2014")
println("  - k_CCL2_sec_Steube1999_proxy")
println("  - q_Treg_T_in_extravasation_PDAC")
println("  - k_apsc_death_melatoninPSC_Estaras2021")
println("  - q_CD8_T_in_yorty2007_sv11_brain_tumor")
println("  - k_psc_activation_apte1998")
println("  - k_Mac_rec_PDAC_M1_recruitment_Gu2023")
println("  - N_IL2_CD4_division_destiny_Gett1998")
println("  - k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015")
println("  - k_MDSC_rec_oscc_ccl2_oo2022")
println("  - n_CD8_clones_Meng2023_PDAC")
println("  - N_IL2_CD8_division_generations_castro2012")
println("  - k_Mac_rec_PDAC_TAM_recruitment_Chen2015")
println("  - k_apsc_death_RA_Xiao2015")
println("  - q_CD8_T_in_extravasation_boissonnas2007")
println("  - k_CCL2_sec_Fujita2010_PrSC")
println("  - k_M1_pol_repolarization_horhold2020")
println("  - k_C1_growth_pdac_human_vdt_ahn2017")
println("  - q_Treg_T_in_Tremblay2017_MRIcelltracking")
println("\nParameters to estimate:")
println("  k_M1_pol (1/day) - constrained by: k_M1_pol_Watkins2007_IL12_TAM_reprogramming, k_M1_pol_repolarization_horhold2020")
println("  k_CCL2_sec (nanomole/cell/day) - constrained by: k_CCL2_sec_bcproxy_yoshimura2023, k_CCL2_sec_Steube1999_proxy, k_CCL2_sec_Fujita2010_PrSC")
println("  k_C1_growth (1/day) - constrained by: k_C1_growth_pdac_tumor_doubling_jang2015, k_C1_growth_pdac_human_vdt_ahn2017")
println("  q_Treg_T_in (1/(centimeter^3*minute)) - constrained by: q_Treg_T_in_PDAC_Tang2014, q_Treg_T_in_extravasation_PDAC, q_Treg_T_in_Tremblay2017_MRIcelltracking")
println("  k_apsc_death (1/day) - constrained by: k_apsc_death_melatoninPSC_Estaras2021, k_apsc_death_RA_Xiao2015")
println("  q_CD8_T_in (1/(centimeter^3*minute)) - constrained by: q_CD8_T_in_yorty2007_sv11_brain_tumor, q_CD8_T_in_extravasation_boissonnas2007")
println("  k_psc_activation (1/day) - constrained by: k_psc_activation_apte1998")
println("  k_Mac_rec (cell/(milliliter*day)) - constrained by: k_Mac_rec_PDAC_M1_recruitment_Gu2023, k_Mac_rec_PDAC_TAM_recruitment_Chen2015")
println("  N_IL2_CD4 (dimensionless) - constrained by: N_IL2_CD4_division_destiny_Gett1998")
println("  k_MDSC_rec (cell/(milliliter*day)) - constrained by: k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015, k_MDSC_rec_oscc_ccl2_oo2022")
println("  n_CD8_clones (dimensionless) - constrained by: n_CD8_clones_Meng2023_PDAC")
println("  N_IL2_CD8 (dimensionless) - constrained by: N_IL2_CD8_division_generations_castro2012")

println("\nSampling with NUTS...")
chain = sample(model, NUTS(0.65), MCMCThreads(), 1000, 4; progress=true)

println("\n" * "=" ^ 60)
println("POSTERIOR SUMMARY")
println("=" ^ 60)
display(chain)

# Convergence diagnostics
println("\nConvergence diagnostics:")
params = [:k_M1_pol, :k_CCL2_sec, :k_C1_growth, :q_Treg_T_in, :k_apsc_death, :q_CD8_T_in, :k_psc_activation, :k_Mac_rec, :N_IL2_CD4, :k_MDSC_rec, :n_CD8_clones, :N_IL2_CD8]
for p in params
    rhat_val = rhat(chain[p])[1]
    ess_val = ess(chain[p])[1]
    status = rhat_val < 1.01 ? "✓" : "⚠"
    println("  $p: R-hat=$(round(rhat_val, digits=3)) $status, ESS=$(round(ess_val, digits=0))")
end

println("\n" * "=" ^ 60)
println("POSTERIOR MEDIANS AND 90% CI")
println("=" ^ 60)
let samples = chain[:k_M1_pol][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_M1_pol: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_CCL2_sec][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_CCL2_sec: $med (nanomole/cell/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_C1_growth][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_C1_growth: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:q_Treg_T_in][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  q_Treg_T_in: $med (1/(centimeter^3*minute))  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_apsc_death][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_apsc_death: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:q_CD8_T_in][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  q_CD8_T_in: $med (1/(centimeter^3*minute))  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_psc_activation][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_psc_activation: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_Mac_rec][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_Mac_rec: $med (cell/(milliliter*day))  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:N_IL2_CD4][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  N_IL2_CD4: $med (dimensionless)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_MDSC_rec][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_MDSC_rec: $med (cell/(milliliter*day))  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:n_CD8_clones][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  n_CD8_clones: $med (dimensionless)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:N_IL2_CD8][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  N_IL2_CD8: $med (dimensionless)  [90% CI: $ci_lo - $ci_hi]")
end

# Plot marginal posteriors with priors
println("\nPlotting marginal posteriors...")

param_names = [:k_M1_pol, :k_CCL2_sec, :k_C1_growth, :q_Treg_T_in, :k_apsc_death, :q_CD8_T_in, :k_psc_activation, :k_Mac_rec, :N_IL2_CD4, :k_MDSC_rec, :n_CD8_clones, :N_IL2_CD8]
param_labels = ["k_M1_pol", "k_CCL2_sec", "k_C1_growth", "q_Treg_T_in", "k_apsc_death", "q_CD8_T_in", "k_psc_activation", "k_Mac_rec", "N_IL2_CD4", "k_MDSC_rec", "n_CD8_clones", "N_IL2_CD8"]

priors = Dict(
    :k_M1_pol => LogNormal(3.0, 1.7),
    :k_CCL2_sec => LogNormal(-20.64, 2.5),
    :k_C1_growth => LogNormal(-5.0, 1.0),
    :q_Treg_T_in => LogNormal(-7.64, 1.7),
    :k_apsc_death => LogNormal(-2.65, 1.7),
    :q_CD8_T_in => LogNormal(-8.0, 3.4),
    :k_psc_activation => LogNormal(-0.693, 1.0),
    :k_Mac_rec => LogNormal(14.66, 1.0),
    :N_IL2_CD4 => Normal(8.0, 2.0),
    :k_MDSC_rec => LogNormal(17.44, 2.5),
    :n_CD8_clones => LogNormal(2.3, 1.0),
    :N_IL2_CD8 => Normal(5.0, 2.0)
)

plots = []
for (i, pname) in enumerate(param_names)
    samples = vec(chain[pname])
    med = median(samples)
    ci_lo = quantile(samples, 0.05)
    ci_hi = quantile(samples, 0.95)

    # X range based on posterior samples
    xmin, xmax = quantile(samples, 0.001), quantile(samples, 0.999)
    xrange = range(xmin, xmax, length=200)

    # Prior density
    prior_dist = priors[pname]
    prior_pdf = pdf.(prior_dist, xrange)

    # Start with prior (gray, underneath)
    plt = plot(xrange, prior_pdf;
        fill=true, fillalpha=0.2, color=:gray, linewidth=1, linecolor=:gray,
        xlabel=param_labels[i], ylabel="",
        label="Prior", legend=false, grid=false, framestyle=:box,
        xrotation=45)

    # Overlay posterior density
    density!(plt, samples;
        fill=true, fillalpha=0.4, color=:steelblue, linewidth=2,
        label="Posterior")

    # Add median and CI lines
    vline!(plt, [med]; color=:red, linewidth=2, linestyle=:solid, label="")
    vline!(plt, [ci_lo, ci_hi]; color=:red, linewidth=1, linestyle=:dash, label="")

    push!(plots, plt)
end

p = plot(plots...; layout=(4, 3), size=(1200, 1000), margin=8mm)
savefig(p, "posterior_marginals.png")
println("Saved: posterior_marginals.png")

# ======================================================================
# SAVE RESULTS TO JSON FOR AUTOMATED PROCESSING
# ======================================================================
using JSON

results = Dict(
    "n_chains" => 4,
    "n_samples" => 1000,
    "parameters" => Dict()
)

# Store raw samples for plotting
posterior_samples = Dict{String, Vector{Float64}}()

for pname in param_names
    samples = vec(chain[pname])
    rhat_val = rhat(chain[pname])[1]
    ess_bulk = ess(chain[pname])[1]
    ess_tail = ess(chain[pname]; kind=:tail)[1]

    # Store raw samples
    posterior_samples[string(pname)] = samples

    results["parameters"][string(pname)] = Dict(
        "median" => median(samples),
        "mean" => mean(samples),
        "std" => std(samples),
        "ci_05" => quantile(samples, 0.05),
        "ci_95" => quantile(samples, 0.95),
        "ci_025" => quantile(samples, 0.025),
        "ci_975" => quantile(samples, 0.975),
        "rhat" => rhat_val,
        "ess_bulk" => ess_bulk,
        "ess_tail" => ess_tail
    )
end

open("inference_results.json", "w") do f
    JSON.print(f, results, 2)
end
println("\nSaved: inference_results.json")

# Save raw posterior samples for plotting
open("posterior_samples.json", "w") do f
    JSON.print(f, posterior_samples, 2)
end
println("Saved: posterior_samples.json")
