# Auto-generated Joint Inference Script
# Generated by: qsp_llm_workflows.julia_translator
#
# Targets:
#   - psc_proliferation_PDAC_deriv001
#   - psc_death_activated_PDAC_deriv002
#   - psc_activation_rate_PDAC_deriv001
#   - psc_recruitment_const_PDAC_deriv001
#   - psc_recruitment_encounter_PDAC_deriv001

using Turing
using DifferentialEquations
using Distributions
using StatsPlots
using Random

Random.seed!(42)

# ======================================================================
# OBSERVED DATA
# ======================================================================

# psc_proliferation_PDAC_deriv001
const PROLIF_OBS_MEDIAN = 4.336397786464344
const PROLIF_OBS_SIGMA = 0.4920139439229736
const PROLIF_T_SPAN = (0.0, 1.0)
const PROLIF_Y0 = 1.0

# psc_death_activated_PDAC_deriv002
const DEATH_OBS_MEDIAN = 0.08617697682570619
const DEATH_OBS_SIGMA = 0.02212267654073389
const DEATH_T_SPAN = (0.0, 28.0)
const DEATH_Y0 = 1.0

# psc_activation_rate_PDAC_deriv001
const ACTIV_OBS_MEDIAN = 0.9502038760179214
const ACTIV_OBS_SIGMA = 0.03718761008640512
const ACTIV_T_SPAN = (0.0, 2.0)
const ACTIV_Y0 = [1.0, 0.0]

# psc_recruitment_const_PDAC_deriv001
const CONST_OBS_MEDIAN = 37225279.28277887
const CONST_OBS_SIGMA = 15753991.134203458

# psc_recruitment_encounter_PDAC_deriv001
const RECRUIT_OBS_MEDIAN_1 = 0.29126796017218964
const RECRUIT_OBS_SIGMA_1 = 0.0699626764589588
const RECRUIT_T_EVAL_1 = 56.0
const RECRUIT_OBS_MEDIAN_2 = 0.4401616242547896
const RECRUIT_OBS_SIGMA_2 = 0.10001324909708109
const RECRUIT_T_EVAL_2 = 70.0
const RECRUIT_T_SPAN = (28.0, 70.0)
const RECRUIT_Y0 = 0.15

# ======================================================================
# ODE SUBMODELS
# ======================================================================

# psc_proliferation_PDAC_deriv001

function psc_proliferation_PDAC_deriv001_ode!(du, u, p, t)
    k_apsc_prolif = p[1]
    du[1] = k_apsc_prolif * u[1]
end


# psc_death_activated_PDAC_deriv002

function psc_death_activated_PDAC_deriv002_ode!(du, u, p, t)
    k_apsc_death = p[1]
    du[1] = -k_apsc_death * u[1]
end


# psc_activation_rate_PDAC_deriv001

function psc_activation_rate_PDAC_deriv001_ode!(du, u, p, t)
    k_psc_activation = p[1]
    du[1] = -k_psc_activation * u[1]  # A -> B
    du[2] = k_psc_activation * u[1]   # A -> B
end


# psc_recruitment_encounter_PDAC_deriv001
function recruitment_ode!(du, u, p, t)
    # p = [k_psc_encounter, k_psc_const]
    k_psc_encounter, k_psc_const = p
    k_eff = k_psc_encounter / k_psc_const
    du[1] = k_eff * (1.0 - u[1])
end


# ======================================================================
# SIMULATION FUNCTIONS
# ======================================================================

function simulate_psc_proliferation_PDAC_deriv001(k_apsc_prolif)
    prob = ODEProblem(psc_proliferation_PDAC_deriv001_ode!, [PROLIF_Y0...], PROLIF_T_SPAN, [k_apsc_prolif])
    sol = solve(prob, AutoTsit5(Rosenbrock23());
                saveat=[PROLIF_T_SPAN[2]],
                abstol=1e-8, reltol=1e-6, maxiters=1e6)
    return sol[1, end]
end


function simulate_psc_death_activated_PDAC_deriv002(k_apsc_death)
    prob = ODEProblem(psc_death_activated_PDAC_deriv002_ode!, [DEATH_Y0...], DEATH_T_SPAN, [k_apsc_death])
    sol = solve(prob, AutoTsit5(Rosenbrock23());
                saveat=[DEATH_T_SPAN[2]],
                abstol=1e-8, reltol=1e-6, maxiters=1e6)
    return sol[1, end]
end


function simulate_psc_activation_rate_PDAC_deriv001(k_psc_activation)
    prob = ODEProblem(psc_activation_rate_PDAC_deriv001_ode!, [ACTIV_Y0...], ACTIV_T_SPAN, [k_psc_activation])
    sol = solve(prob, AutoTsit5(Rosenbrock23());
                saveat=[ACTIV_T_SPAN[2]],
                abstol=1e-8, reltol=1e-6, maxiters=1e6)
    return sol[2, end] / (sol[1, end] + sol[2, end])
end


function simulate_psc_recruitment_encounter_PDAC_deriv001(k_psc_encounter, k_psc_const)
    prob = ODEProblem(recruitment_ode!, [RECRUIT_Y0...], RECRUIT_T_SPAN, [k_psc_encounter, k_psc_const])
    sol = solve(prob, AutoTsit5(Rosenbrock23());
                saveat=[RECRUIT_T_EVAL_1, RECRUIT_T_EVAL_2],
                abstol=1e-8, reltol=1e-6, maxiters=1e6)
    return [sol(t)[1] for t in [RECRUIT_T_EVAL_1, RECRUIT_T_EVAL_2]]
end


# ======================================================================
# JOINT TURING MODEL
# ======================================================================
@model function joint_calibration(prolif_obs, prolif_sigma, death_obs, death_sigma, activ_obs, activ_sigma, const_obs, const_sigma, recruit_obs, recruit_sigmas)
    # =========================================
    # PRIORS (shared across targets)
    # =========================================
    k_apsc_prolif ~ LogNormal(0.0, 1.0)  # Used by: psc_proliferation_PDAC_deriv001
    k_apsc_death ~ LogNormal(-1.897, 0.5)  # Used by: psc_death_activated_PDAC_deriv002
    k_psc_activation ~ LogNormal(1.099, 0.5)  # Used by: psc_activation_rate_PDAC_deriv001
    k_psc_const ~ LogNormal(17.425, 1.0)  # Used by: psc_recruitment_const_PDAC_deriv001, psc_recruitment_encounter_PDAC_deriv001
    k_psc_encounter ~ LogNormal(13.816, 2.0)  # Used by: psc_recruitment_encounter_PDAC_deriv001

    # =========================================
    # LIKELIHOODS
    # =========================================

    # psc_proliferation_PDAC_deriv001
    pred_prolif = simulate_psc_proliferation_PDAC_deriv001(k_apsc_prolif)
    prolif_obs ~ Normal(pred_prolif, prolif_sigma)

    # psc_death_activated_PDAC_deriv002
    pred_death = simulate_psc_death_activated_PDAC_deriv002(k_apsc_death)
    death_obs ~ Normal(pred_death, death_sigma)

    # psc_activation_rate_PDAC_deriv001
    pred_activ = simulate_psc_activation_rate_PDAC_deriv001(k_psc_activation)
    activ_obs ~ Normal(pred_activ, activ_sigma)

    # psc_recruitment_const_PDAC_deriv001
    const_obs ~ Normal(k_psc_const, const_sigma)

    # psc_recruitment_encounter_PDAC_deriv001
    pred_recruit = simulate_psc_recruitment_encounter_PDAC_deriv001(k_psc_encounter, k_psc_const)
    for i in eachindex(recruit_obs)
        recruit_obs[i] ~ Normal(pred_recruit[i], recruit_sigmas[i])
    end

    return (k_apsc_prolif=k_apsc_prolif, k_apsc_death=k_apsc_death, k_psc_activation=k_psc_activation, k_psc_const=k_psc_const, k_psc_encounter=k_psc_encounter)
end

# ======================================================================
# RUN INFERENCE
# ======================================================================

model = joint_calibration(PROLIF_OBS_MEDIAN, PROLIF_OBS_SIGMA, DEATH_OBS_MEDIAN, DEATH_OBS_SIGMA, ACTIV_OBS_MEDIAN, ACTIV_OBS_SIGMA, CONST_OBS_MEDIAN, CONST_OBS_SIGMA, [RECRUIT_OBS_MEDIAN_1, RECRUIT_OBS_MEDIAN_2], [RECRUIT_OBS_SIGMA_1, RECRUIT_OBS_SIGMA_2])

println("=" ^ 60)
println("JOINT BAYESIAN CALIBRATION")
println("=" ^ 60)
println("\nParameters to estimate:")
println("  k_apsc_prolif (1/day) - constrained by: psc_proliferation_PDAC_deriv001")
println("  k_apsc_death (1/day) - constrained by: psc_death_activated_PDAC_deriv002")
println("  k_psc_activation (1/day) - constrained by: psc_activation_rate_PDAC_deriv001")
println("  k_psc_const (cell/milliliter) - constrained by: psc_recruitment_const_PDAC_deriv001, psc_recruitment_encounter_PDAC_deriv001")
println("  k_psc_encounter (cell/(milliliter*day)) - constrained by: psc_recruitment_encounter_PDAC_deriv001")

println("\nSampling with NUTS...")
chain = sample(model, NUTS(0.65), MCMCThreads(), 1000, 4; progress=true)

println("\n" * "=" ^ 60)
println("POSTERIOR SUMMARY")
println("=" ^ 60)
display(chain)

# Convergence diagnostics
println("\nConvergence diagnostics:")
params = [:k_apsc_prolif, :k_apsc_death, :k_psc_activation, :k_psc_const, :k_psc_encounter]
for p in params
    rhat_val = rhat(chain[p])[1]
    ess_val = ess(chain[p])[1]
    status = rhat_val < 1.01 ? "✓" : "⚠"
    println("  $p: R-hat=$(round(rhat_val, digits=3)) $status, ESS=$(round(ess_val, digits=0))")
end

println("\n" * "=" ^ 60)
println("POSTERIOR MEDIANS")
println("=" ^ 60)
println("  k_apsc_prolif: $(round(median(chain[:k_apsc_prolif][:]), sigdigits=4)) 1/day")
println("  k_apsc_death: $(round(median(chain[:k_apsc_death][:]), sigdigits=4)) 1/day")
println("  k_psc_activation: $(round(median(chain[:k_psc_activation][:]), sigdigits=4)) 1/day")
println("  k_psc_const: $(round(median(chain[:k_psc_const][:]), sigdigits=4)) cell/milliliter")
println("  k_psc_encounter: $(round(median(chain[:k_psc_encounter][:]), sigdigits=4)) cell/(milliliter*day)")