# Auto-generated Joint Inference Script
# Generated by: qsp_llm_workflows.julia_translator
#
# Targets:
#   - ecm_secretion_apsc_PDAC_deriv001
#   - psc_activation_rate_PDAC_deriv001
#   - psc_death_activated_PDAC_deriv002
#   - psc_death_quiescent_PDAC_deriv001
#   - psc_proliferation_PDAC_deriv001
#   - psc_recruitment_const_PDAC_deriv001
#   - psc_recruitment_encounter_PDAC_deriv001
#   - tcell_kill_probability_PDAC_deriv001
#   - tgfb_secretion_apsc_PDAC_deriv001
#   - treg_suppression_r50_PDAC_deriv001

using Turing
using DifferentialEquations
using Distributions
using StatsPlots
using Random

Random.seed!(42)

# ======================================================================
# OBSERVED DATA (Dict keyed by target_id)
# ======================================================================

const DATA = Dict(
    "ecm_secretion_apsc_PDAC_deriv001" => (
        obs_median = [6.476846072441413e-10],
        obs_sigma = [3.288059867916999e-10],
        t_eval = [0.0],
    ),
    "psc_activation_rate_PDAC_deriv001" => (
        obs_median = [0.9502038760179214],
        obs_sigma = [0.03718761008640512],
        t_span = (0.0, 2.0),
        t_eval = [2.0],
        y0 = [1.0, 0.0],
    ),
    "psc_death_activated_PDAC_deriv002" => (
        obs_median = [0.08617697682570619],
        obs_sigma = [0.02212267654073389],
        t_span = (0.0, 28.0),
        t_eval = [28.0],
        y0 = [1.0],
    ),
    "psc_death_quiescent_PDAC_deriv001" => (
        obs_median = [0.19833079442427248],
        obs_sigma = [0.04924527871929393],
        t_eval = [0.0],
    ),
    "psc_proliferation_PDAC_deriv001" => (
        obs_median = [4.336397786464344],
        obs_sigma = [0.4920139439229736],
        t_span = (0.0, 1.0),
        t_eval = [1.0],
        y0 = [1.0],
    ),
    "psc_recruitment_const_PDAC_deriv001" => (
        obs_median = [37225279.28277887],
        obs_sigma = [15753991.134203458],
    ),
    "psc_recruitment_encounter_PDAC_deriv001" => (
        obs_median = [0.29126796017218964, 0.4401616242547896],
        obs_sigma = [0.0699626764589588, 0.10001324909708109],
        t_span = (28.0, 70.0),
        t_eval = [56.0, 70.0],
        y0 = [0.15],
    ),
    "tcell_kill_probability_PDAC_deriv001" => (
        obs_median = [0.15039789924002456],
        obs_sigma = [0.02752379313035153],
        t_eval = [0.0],
    ),
    "tgfb_secretion_apsc_PDAC_deriv001" => (
        obs_median = [4.2536684572447596e-10],
        obs_sigma = [1.8266854941205285e-10],
        t_eval = [0.0],
    ),
    "treg_suppression_r50_PDAC_deriv001" => (
        obs_median = [0.5068293001008572],
        obs_sigma = [0.14467787897753365],
        t_eval = [0.25],
    )
)


# ======================================================================
# ODE SUBMODELS
# ======================================================================

# psc_activation_rate_PDAC_deriv001

function psc_activation_rate_PDAC_deriv001_ode!(du, u, p, t)
    k_psc_activation = p[1]
    du[1] = -k_psc_activation * u[1]  # A -> B
    du[2] = k_psc_activation * u[1]   # A -> B
end


# psc_death_activated_PDAC_deriv002

function psc_death_activated_PDAC_deriv002_ode!(du, u, p, t)
    k_apsc_death = p[1]
    du[1] = -k_apsc_death * u[1]
end


# psc_proliferation_PDAC_deriv001

function psc_proliferation_PDAC_deriv001_ode!(du, u, p, t)
    k_apsc_prolif = p[1]
    du[1] = k_apsc_prolif * u[1]
end


# psc_recruitment_encounter_PDAC_deriv001
function recruitment_ode!(du, u, p, t)
    # p = [k_psc_encounter, k_psc_const]
    k_psc_encounter, k_psc_const = p
    k_eff = k_psc_encounter / k_psc_const
    du[1] = k_eff * (1.0 - u[1])
end


# ======================================================================
# SIMULATION FUNCTIONS
# ======================================================================

function simulate_psc_activation_rate_PDAC_deriv001(k_psc_activation)
    d = DATA["psc_activation_rate_PDAC_deriv001"]
    prob = ODEProblem(psc_activation_rate_PDAC_deriv001_ode!, d.y0, d.t_span, [k_psc_activation])
    sol = solve(prob, AutoTsit5(Rosenbrock23());
                saveat=[DATA["psc_activation_rate_PDAC_deriv001"].t_span[2]],
                abstol=1e-8, reltol=1e-6, maxiters=1e6)
    return sol[2, end] / (sol[1, end] + sol[2, end])
end


function simulate_psc_death_activated_PDAC_deriv002(k_apsc_death)
    d = DATA["psc_death_activated_PDAC_deriv002"]
    prob = ODEProblem(psc_death_activated_PDAC_deriv002_ode!, d.y0, d.t_span, [k_apsc_death])
    sol = solve(prob, AutoTsit5(Rosenbrock23());
                saveat=[DATA["psc_death_activated_PDAC_deriv002"].t_span[2]],
                abstol=1e-8, reltol=1e-6, maxiters=1e6)
    return sol[1, end]
end


function simulate_psc_proliferation_PDAC_deriv001(k_apsc_prolif)
    d = DATA["psc_proliferation_PDAC_deriv001"]
    prob = ODEProblem(psc_proliferation_PDAC_deriv001_ode!, d.y0, d.t_span, [k_apsc_prolif])
    sol = solve(prob, AutoTsit5(Rosenbrock23());
                saveat=[DATA["psc_proliferation_PDAC_deriv001"].t_span[2]],
                abstol=1e-8, reltol=1e-6, maxiters=1e6)
    return sol[1, end]
end


function simulate_psc_recruitment_encounter_PDAC_deriv001(k_psc_encounter, k_psc_const)
    d = DATA["psc_recruitment_encounter_PDAC_deriv001"]
    prob = ODEProblem(recruitment_ode!, d.y0, d.t_span, [k_psc_encounter, k_psc_const])
    sol = solve(prob, AutoTsit5(Rosenbrock23());
                saveat=DATA["psc_recruitment_encounter_PDAC_deriv001"].t_eval,
                abstol=1e-8, reltol=1e-6, maxiters=1e6)
    return [sol(t)[1] for t in DATA["psc_recruitment_encounter_PDAC_deriv001"].t_eval]
end


# ======================================================================
# JOINT TURING MODEL
# ======================================================================
@model function joint_calibration(data)
    # =========================================
    # PRIORS (shared across targets)
    # =========================================
    k_ECM_apsc_sec ~ LogNormal(-15.0, 1.5)  # Used by: ecm_secretion_apsc_PDAC_deriv001
    k_psc_activation ~ LogNormal(1.099, 0.5)  # Used by: psc_activation_rate_PDAC_deriv001
    k_apsc_death ~ LogNormal(-1.897, 0.5)  # Used by: psc_death_activated_PDAC_deriv002
    k_qpsc_death ~ LogNormal(-1.897, 0.5)  # Used by: psc_death_quiescent_PDAC_deriv001
    k_apsc_prolif ~ LogNormal(0.0, 1.0)  # Used by: psc_proliferation_PDAC_deriv001
    k_psc_const ~ LogNormal(17.425, 1.0)  # Used by: psc_recruitment_const_PDAC_deriv001, psc_recruitment_encounter_PDAC_deriv001
    k_psc_encounter ~ LogNormal(13.816, 2.0)  # Used by: psc_recruitment_encounter_PDAC_deriv001
    p_T_kill_per_contact ~ Uniform(0.01, 0.5)  # Used by: tcell_kill_probability_PDAC_deriv001
    k_TGFb_sec_apsc ~ LogNormal(-21.0, 1.5)  # Used by: tgfb_secretion_apsc_PDAC_deriv001
    R50_Treg ~ LogNormal(-1.2, 0.5)  # Used by: treg_suppression_r50_PDAC_deriv001

    # =========================================
    # LIKELIHOODS
    # =========================================

    # ecm_secretion_apsc_PDAC_deriv001
    data["ecm_secretion_apsc_PDAC_deriv001"].obs_median[1] ~ Normal(k_ECM_apsc_sec, data["ecm_secretion_apsc_PDAC_deriv001"].obs_sigma[1])

    # psc_activation_rate_PDAC_deriv001
    pred_psc_activation_rate_PDAC_deriv001 = simulate_psc_activation_rate_PDAC_deriv001(k_psc_activation)
    data["psc_activation_rate_PDAC_deriv001"].obs_median[1] ~ Normal(pred_psc_activation_rate_PDAC_deriv001, data["psc_activation_rate_PDAC_deriv001"].obs_sigma[1])

    # psc_death_activated_PDAC_deriv002
    pred_psc_death_activated_PDAC_deriv002 = simulate_psc_death_activated_PDAC_deriv002(k_apsc_death)
    data["psc_death_activated_PDAC_deriv002"].obs_median[1] ~ Normal(pred_psc_death_activated_PDAC_deriv002, data["psc_death_activated_PDAC_deriv002"].obs_sigma[1])

    # psc_death_quiescent_PDAC_deriv001
    data["psc_death_quiescent_PDAC_deriv001"].obs_median[1] ~ Normal(k_qpsc_death, data["psc_death_quiescent_PDAC_deriv001"].obs_sigma[1])

    # psc_proliferation_PDAC_deriv001
    pred_psc_proliferation_PDAC_deriv001 = simulate_psc_proliferation_PDAC_deriv001(k_apsc_prolif)
    data["psc_proliferation_PDAC_deriv001"].obs_median[1] ~ Normal(pred_psc_proliferation_PDAC_deriv001, data["psc_proliferation_PDAC_deriv001"].obs_sigma[1])

    # psc_recruitment_const_PDAC_deriv001
    data["psc_recruitment_const_PDAC_deriv001"].obs_median[1] ~ Normal(k_psc_const, data["psc_recruitment_const_PDAC_deriv001"].obs_sigma[1])

    # psc_recruitment_encounter_PDAC_deriv001
    pred_psc_recruitment_encounter_PDAC_deriv001 = simulate_psc_recruitment_encounter_PDAC_deriv001(k_psc_encounter, k_psc_const)
    for i in 1:2
        data["psc_recruitment_encounter_PDAC_deriv001"].obs_median[i] ~ Normal(pred_psc_recruitment_encounter_PDAC_deriv001[i], data["psc_recruitment_encounter_PDAC_deriv001"].obs_sigma[i])
    end

    # tcell_kill_probability_PDAC_deriv001
    data["tcell_kill_probability_PDAC_deriv001"].obs_median[1] ~ Normal(p_T_kill_per_contact, data["tcell_kill_probability_PDAC_deriv001"].obs_sigma[1])

    # tgfb_secretion_apsc_PDAC_deriv001
    data["tgfb_secretion_apsc_PDAC_deriv001"].obs_median[1] ~ Normal(k_TGFb_sec_apsc, data["tgfb_secretion_apsc_PDAC_deriv001"].obs_sigma[1])

    # treg_suppression_r50_PDAC_deriv001
    data["treg_suppression_r50_PDAC_deriv001"].obs_median[1] ~ Normal(R50_Treg, data["treg_suppression_r50_PDAC_deriv001"].obs_sigma[1])

    return (k_ECM_apsc_sec=k_ECM_apsc_sec, k_psc_activation=k_psc_activation, k_apsc_death=k_apsc_death, k_qpsc_death=k_qpsc_death, k_apsc_prolif=k_apsc_prolif, k_psc_const=k_psc_const, k_psc_encounter=k_psc_encounter, p_T_kill_per_contact=p_T_kill_per_contact, k_TGFb_sec_apsc=k_TGFb_sec_apsc, R50_Treg=R50_Treg)
end

# ======================================================================
# RUN INFERENCE
# ======================================================================

model = joint_calibration(DATA)

println("=" ^ 60)
println("JOINT BAYESIAN CALIBRATION")
println("=" ^ 60)
println("\nTargets:")
println("  - ecm_secretion_apsc_PDAC_deriv001")
println("  - psc_activation_rate_PDAC_deriv001")
println("  - psc_death_activated_PDAC_deriv002")
println("  - psc_death_quiescent_PDAC_deriv001")
println("  - psc_proliferation_PDAC_deriv001")
println("  - psc_recruitment_const_PDAC_deriv001")
println("  - psc_recruitment_encounter_PDAC_deriv001")
println("  - tcell_kill_probability_PDAC_deriv001")
println("  - tgfb_secretion_apsc_PDAC_deriv001")
println("  - treg_suppression_r50_PDAC_deriv001")
println("\nParameters to estimate:")
println("  k_ECM_apsc_sec (milligram / (cell * day)) - constrained by: ecm_secretion_apsc_PDAC_deriv001")
println("  k_psc_activation (1/day) - constrained by: psc_activation_rate_PDAC_deriv001")
println("  k_apsc_death (1/day) - constrained by: psc_death_activated_PDAC_deriv002")
println("  k_qpsc_death (1/day) - constrained by: psc_death_quiescent_PDAC_deriv001")
println("  k_apsc_prolif (1/day) - constrained by: psc_proliferation_PDAC_deriv001")
println("  k_psc_const (cell/milliliter) - constrained by: psc_recruitment_const_PDAC_deriv001, psc_recruitment_encounter_PDAC_deriv001")
println("  k_psc_encounter (cell/(milliliter*day)) - constrained by: psc_recruitment_encounter_PDAC_deriv001")
println("  p_T_kill_per_contact (dimensionless) - constrained by: tcell_kill_probability_PDAC_deriv001")
println("  k_TGFb_sec_apsc (nanomolarity * liter / (cell * day)) - constrained by: tgfb_secretion_apsc_PDAC_deriv001")
println("  R50_Treg (dimensionless) - constrained by: treg_suppression_r50_PDAC_deriv001")

println("\nSampling with NUTS...")
chain = sample(model, NUTS(0.65), MCMCThreads(), 1000, 4; progress=true)

println("\n" * "=" ^ 60)
println("POSTERIOR SUMMARY")
println("=" ^ 60)
display(chain)

# Convergence diagnostics
println("\nConvergence diagnostics:")
params = [:k_ECM_apsc_sec, :k_psc_activation, :k_apsc_death, :k_qpsc_death, :k_apsc_prolif, :k_psc_const, :k_psc_encounter, :p_T_kill_per_contact, :k_TGFb_sec_apsc, :R50_Treg]
for p in params
    rhat_val = rhat(chain[p])[1]
    ess_val = ess(chain[p])[1]
    status = rhat_val < 1.01 ? "✓" : "⚠"
    println("  $p: R-hat=$(round(rhat_val, digits=3)) $status, ESS=$(round(ess_val, digits=0))")
end

println("\n" * "=" ^ 60)
println("POSTERIOR MEDIANS")
println("=" ^ 60)
println("  k_ECM_apsc_sec: $(round(median(chain[:k_ECM_apsc_sec][:]), sigdigits=4)) milligram / (cell * day)")
println("  k_psc_activation: $(round(median(chain[:k_psc_activation][:]), sigdigits=4)) 1/day")
println("  k_apsc_death: $(round(median(chain[:k_apsc_death][:]), sigdigits=4)) 1/day")
println("  k_qpsc_death: $(round(median(chain[:k_qpsc_death][:]), sigdigits=4)) 1/day")
println("  k_apsc_prolif: $(round(median(chain[:k_apsc_prolif][:]), sigdigits=4)) 1/day")
println("  k_psc_const: $(round(median(chain[:k_psc_const][:]), sigdigits=4)) cell/milliliter")
println("  k_psc_encounter: $(round(median(chain[:k_psc_encounter][:]), sigdigits=4)) cell/(milliliter*day)")
println("  p_T_kill_per_contact: $(round(median(chain[:p_T_kill_per_contact][:]), sigdigits=4)) dimensionless")
println("  k_TGFb_sec_apsc: $(round(median(chain[:k_TGFb_sec_apsc][:]), sigdigits=4)) nanomolarity * liter / (cell * day)")
println("  R50_Treg: $(round(median(chain[:R50_Treg][:]), sigdigits=4)) dimensionless")