# Auto-generated Joint Inference Script
# Generated by: qsp_llm_workflows.julia_translator
#
# Targets:
#   - N_IL2_CD4_division_destiny_Gett1998
#   - N_IL2_CD8_division_generations_castro2012
#   - k_C1_growth_pdac_human_vdt_ahn2017
#   - k_C1_growth_pdac_tumor_doubling_jang2015
#   - k_CCL2_sec_Fujita2010_PrSC
#   - k_CCL2_sec_Steube1999_proxy
#   - k_CCL2_sec_bcproxy_yoshimura2023
#   - k_CCL2_sec_psc_michalski2008
#   - k_CCL2_sec_pdac_plasma_Nixon2013
#   - k_M1_pol_Watkins2007_IL12_TAM_reprogramming
#   - k_M1_pol_repolarization_horhold2020
#   - k_M1_pol_rp182_m2_to_m1_repolarization
#   - k_M1_pol_pdac_cd86_cd163_gu2023
#   - k_M1_pol_steady_state_ratio_DLBCL2021
#   - k_M1_pol_pdac_m1m2ratio_DeSimoni2023
#   - k_M1_pol_tam_ratio_herwig2013
#   - k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015
#   - k_MDSC_rec_oscc_ccl2_oo2022
#   - k_MDSC_rec_PDAC_Porembka2012
#   - k_MDSC_rec_panc02_spleenexpansion_ghansah2013
#   - k_MDSC_rec_pdac_trovato2019
#   - k_MDSC_rec_panc02_tnfr1_chopra2013
#   - k_Mac_rec_PDAC_M1_recruitment_Gu2023
#   - k_Mac_rec_PDAC_TAM_recruitment_Chen2015
#   - k_Mac_rec_humanPDAC_CD40_2021
#   - k_apsc_death_melatoninPSC_Estaras2021
#   - k_apsc_death_RA_Xiao2015
#   - k_apsc_death_hsc_apoptosis_issa2001
#   - k_psc_activation_apte1998
#   - n_CD8_clones_Meng2023_PDAC
#   - q_CD8_T_in_extravasation_boissonnas2007
#   - q_CD8_T_in_yorty2007_sv11_brain_tumor
#   - q_CD8_T_in_PDAC_CD8density_ModPathol2019
#   - q_Treg_T_in_Tremblay2017_MRIcelltracking
#   - q_Treg_T_in_PDAC_Tang2014
#   - q_Treg_T_in_extravasation_PDAC
#   - q_Treg_T_in_Jiang2014_Liyanage2002

using Turing
using DifferentialEquations
using Distributions
using StatsPlots
using Plots: mm
using Random

Random.seed!(42)

# ======================================================================
# OBSERVED DATA (Dict keyed by target_id)
# ======================================================================

const DATA = Dict(
    "N_IL2_CD4_division_destiny_Gett1998" => (
        obs_median = [8.0],
        obs_sigma = [2.0],
        sd_uncertain = [false],
        likelihood = ["normal"],
        inputs = Dict("max_divisions_cd4_antiCD3_IL2_IL4" => 8, "assumed_cv" => 0.25),
    ),
    "N_IL2_CD8_division_generations_castro2012" => (
        obs_median = [40.0, 70.0],
        obs_sigma = [15.0, 34.0],
        sd_uncertain = [false, false],
        likelihood = ["normal", "normal"],
        inputs = Dict("fold_increase_memory_day10" => 40, "fold_increase_memory_day30" => 70, "fold_increase_memory_day10_sem" => 15, "fold_increase_memory_day30_sem" => 34),
    ),
    "k_C1_growth_pdac_human_vdt_ahn2017" => (
        obs_median = [132.3],
        obs_sigma = [0.8316462380958335],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("vdtime_mean" => 132.3, "vdtime_sd" => 132.1),
    ),
    "k_C1_growth_pdac_tumor_doubling_jang2015" => (
        obs_median = [151.7],
        obs_sigma = [0.9436019284872316],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("jang_vdT_mean" => 151.7, "jang_vdT_min" => 18.3, "jang_vdT_max" => 417.8, "jang_n_patients" => 22),
    ),
    "k_CCL2_sec_Fujita2010_PrSC" => (
        obs_median = [1888.0],
        obs_sigma = [0.325408570007528],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_CCL2_sec_Steube1999_proxy" => (
        obs_median = [784.8566748139433],
        obs_sigma = [0.2952685685436335],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_CCL2_sec_bcproxy_yoshimura2023" => (
        obs_median = [30.0],
        obs_sigma = [0.47238072707743883],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_CCL2_sec_psc_michalski2008" => (
        obs_median = [200.0],
        obs_sigma = [0.3],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_CCL2_sec_pdac_plasma_Nixon2013" => (
        obs_median = [0.060122133886392426],
        obs_sigma = [0.5],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_M1_pol_Watkins2007_IL12_TAM_reprogramming" => (
        obs_median = [0.03125],
        obs_sigma = [0.5605164738102602],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("t_reprogram_max_90min" => 0.0625, "assumed_half_life_fraction" => 0.5, "assumed_fold_uncertainty" => 3),
    ),
    "k_M1_pol_repolarization_horhold2020" => (
        obs_median = [33.94112549695428],
        obs_sigma = [0.17682326034692486],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("m2_to_m1_repol_time_low" => 24, "m2_to_m1_repol_time_high" => 48),
    ),
    "k_M1_pol_rp182_m2_to_m1_repolarization" => (
        obs_median = [0.878],
        obs_sigma = [0.0878],
        sd_uncertain = [false],
        likelihood = ["normal"],
        inputs = Dict("rp182_cd86pos_cd206pos_frac_30min" => 0.878, "rp182_cd86pos_cd206pos_frac_vehicle" => 0.103, "rp182_cd86pos_cd206neg_frac_24h" => 0.106, "rp182_t_30min" => 0.0208333, "rp182_cd86pos_frac_cv" => 0.1, "pdac_primary_cd86_pos_cells_per_hpf_median" => 11.6, "pdac_primary_cd163_pos_cells_per_hpf_median" => 27.1),
    ),
    "k_M1_pol_pdac_cd86_cd163_gu2023" => (
        obs_median = [0.4280442804428044],
        obs_sigma = [0.689723078526698],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_M1_pol_steady_state_ratio_DLBCL2021" => (
        obs_median = [0.7459715639810427],
        obs_sigma = [0.2381266590248728],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_M1_pol_pdac_m1m2ratio_DeSimoni2023" => (
        obs_median = [0.05434782608695652],
        obs_sigma = [0.5],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_M1_pol_tam_ratio_herwig2013" => (
        obs_median = [2.0],
        obs_sigma = [0.25],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015" => (
        obs_median = [8.1],
        obs_sigma = [0.29008531439248997],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("B16_MDSC_fraction_control" => 8.1, "B16_MDSC_fraction_control_sd" => 2.4, "tumor_cell_density" => 1000000000, "MDSC_half_life" => 1.5),
    ),
    "k_MDSC_rec_oscc_ccl2_oo2022" => (
        obs_median = [610.0],
        obs_sigma = [1.2109109281940988],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("bm_cells_migrated_PDS1_9h_per_field" => 610, "migration_time_9h" => 9, "lower_chamber_volume" => 0.75, "imaging_volume_per_field" => 0.01, "bm_cells_initial_upper_chamber" => 500000, "assumed_cv_migrated" => 0.3, "imaging_volume_uncertainty_fold" => 10),
    ),
    "k_MDSC_rec_PDAC_Porembka2012" => (
        obs_median = [0.666],
        obs_sigma = [0.032],
        sd_uncertain = [false],
        likelihood = ["normal"],
    ),
    "k_MDSC_rec_panc02_spleenexpansion_ghansah2013" => (
        obs_median = [0.29],
        obs_sigma = [0.3],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("mdsc_fraction_baseline" => 0.02, "mdsc_fraction_day27" => 0.29, "observation_time_day27" => 27, "spleen_cell_density" => 500000000, "mdsc_fraction_day27_cv" => 0.3),
    ),
    "k_MDSC_rec_pdac_trovato2019" => (
        obs_median = [0.969],
        obs_sigma = [0.17234262125902994],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_MDSC_rec_panc02_tnfr1_chopra2013" => (
        obs_median = [0.1717],
        obs_sigma = [0.8177052999417589],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_Mac_rec_PDAC_M1_recruitment_Gu2023" => (
        obs_median = [59.18367346938775],
        obs_sigma = [0.7008344169019112],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_Mac_rec_PDAC_TAM_recruitment_Chen2015" => (
        obs_median = [301.6877637130802],
        obs_sigma = [0.6600542314828028],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_Mac_rec_humanPDAC_CD40_2021" => (
        obs_median = [1.5660377358490567],
        obs_sigma = [0.3],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "k_apsc_death_melatoninPSC_Estaras2021" => (
        obs_median = [0.8677],
        obs_sigma = [1.9918584287042087],
        sd_uncertain = [false],
        likelihood = ["normal"],
        t_span = (0.0, 2.0),
        t_eval = [2.0],
        y0 = [1.0],
    ),
    "k_apsc_death_RA_Xiao2015" => (
        obs_median = [5.0],
        obs_sigma = [1.0],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("half_life_apsc" => 5, "assumed_sigma_log" => 1),
    ),
    "k_apsc_death_hsc_apoptosis_issa2001" => (
        obs_median = [0.2],
        obs_sigma = [0.3],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        t_span = (0.0, 42.0),
        t_eval = [42.0],
        y0 = [1.0],
    ),
    "k_psc_activation_apte1998" => (
        obs_median = [48.0],
        obs_sigma = [0.24622067706923975],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("psc_activation_time_48h" => 48, "assumed_cv" => 0.25),
    ),
    "n_CD8_clones_Meng2023_PDAC" => (
        obs_median = [93.0],
        obs_sigma = [0.10341803090732268],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("total_TR_clonotypes_Meng2023" => 93, "n_PDAC_tumors_Meng2023" => 9),
    ),
    "q_CD8_T_in_extravasation_boissonnas2007" => (
        obs_median = [327.0],
        obs_sigma = [0.28215854750622943],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("OT1_injected" => 10000000, "EG7_tumor_volume_min" => 500, "EG7_tumor_volume_max" => 1000, "OT1_density_day6" => 327, "OT1_density_day6_sd" => 50, "section_thickness_um" => 5, "CD8_eff_half_life" => 41, "CD8_eff_half_life_sd" => 10),
    ),
    "q_CD8_T_in_yorty2007_sv11_brain_tumor" => (
        obs_median = [5.916079783099616],
        obs_sigma = [0.08583475424010535],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("t_peak_immune_lower" => 5, "t_peak_immune_upper" => 7, "reference_tumor_volume" => 1),
    ),
    "q_CD8_T_in_PDAC_CD8density_ModPathol2019" => (
        obs_median = [166.9],
        obs_sigma = [0.5960521097002373],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    ),
    "q_Treg_T_in_Tremblay2017_MRIcelltracking" => (
        obs_median = [24.0],
        obs_sigma = [0.5605164738102602],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("t_vis_Treg" => 24, "V_T_ref" => 1, "assumed_fold_uncertainty" => 3),
    ),
    "q_Treg_T_in_PDAC_Tang2014" => (
        obs_median = [3.092962641181581],
        obs_sigma = [0.30822138330525917],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("PDAC_TIL_Treg_fraction_mean" => 0.178, "PDAC_TIL_Treg_fraction_sem" => 0.007075, "PBMC_Treg_fraction_mean" => 0.05755, "PBMC_Treg_fraction_sem" => 0.00145, "Treg_doubling_time_mean" => 8, "n_patients" => 45),
    ),
    "q_Treg_T_in_extravasation_PDAC" => (
        obs_median = [0.6869627851140456],
        obs_sigma = [0.3123785017232525],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
        inputs = Dict("treg_density_tumor_panc_120_per_mm2" => 120, "treg_density_adjacent_pancreas_80_per_mm2" => 80, "treg_transmigration_conventional_invitro_cells" => 3332, "treg_transmigration_treg_invitro_cells" => 4976, "cd34_migration_fraction_4h" => 0.46, "migration_time_4h_hr" => 4, "assumed_cv_migration_fraction" => 0.2, "assumed_cv_transmigration_ratio" => 0.25, "max_migration_fraction" => 0.99),
    ),
    "q_Treg_T_in_Jiang2014_Liyanage2002" => (
        obs_median = [7680.0],
        obs_sigma = [0.88112989449011],
        sd_uncertain = [false],
        likelihood = ["lognormal"],
    )
)


# ======================================================================
# ODE SUBMODELS
# ======================================================================

# ======================================================================
# SIMULATION FUNCTIONS
# ======================================================================
function compute_N_IL2_CD4_division_destiny_Gett1998(params, inputs)
    N = params["N_IL2_CD4"]
    return N
end

function compute_N_IL2_CD8_division_generations_castro2012(params, inputs)
    N = params["N_IL2_CD8"]
    fold_increase = 2.0 ^ N
    return fold_increase
end

function compute_k_C1_growth_pdac_human_vdt_ahn2017(params, inputs)
    k = params["k_C1_growth"]
    vdt = log(2) / k
    return vdt  # days
end

function compute_k_C1_growth_pdac_tumor_doubling_jang2015(params, inputs)
    k = params["k_C1_growth"]  # 1/day
    return log(2) / k  # in days
end


# Forward model (batch_accumulation)
function compute_k_CCL2_sec_Fujita2010_PrSC(params, inputs, reference_values)
    sec_rate = params["k_CCL2_sec"]
    cells = inputs["n_cells_prsc"]
    t_inc = inputs["incubation_time_hours"]
    mw = reference_values["ccl2_molecular_weight_mature"]
    ucf = 41.6667
    vol = inputs["V_medium_ml"]
    return sec_rate * cells * t_inc * mw * ucf / vol
end

function simulate_k_CCL2_sec_Fujita2010_PrSC(k_CCL2_sec)
    params = Dict("k_CCL2_sec" => k_CCL2_sec)
    inputs = Dict("CCL2_prsc_unstim_mean" => 1888.0, "CCL2_prsc_unstim_sd" => 631.0, "n_cells_prsc" => 100000.0, "incubation_time_hours" => 48.0, "V_medium_ml" => 1.0)
    reference_values = Dict("ccl2_molecular_weight_mature" => 8679.0)
    return compute_k_CCL2_sec_Fujita2010_PrSC(params, inputs, reference_values)
end


# Forward model (batch_accumulation)
function compute_k_CCL2_sec_Steube1999_proxy(params, inputs, reference_values)
    sec_rate = params["k_CCL2_sec"]
    cells = 1000000.0
    t_inc = 1.0
    mw = reference_values["ccl2_molecular_weight_mature"]
    ucf = 1000.0
    vol = 1.0
    return sec_rate * cells * t_inc * mw * ucf / vol
end

function simulate_k_CCL2_sec_Steube1999_proxy(k_CCL2_sec)
    params = Dict("k_CCL2_sec" => k_CCL2_sec)
    inputs = Dict("mcp1_constitutive_min_pg_per_ml_per_millioncells" => 440.0, "mcp1_constitutive_max_pg_per_ml_per_millioncells" => 1400.0, "mcp1_stimulated_max_ng_per_ml_per_millioncells_24h" => 80.0)
    reference_values = Dict("ccl2_molecular_weight_mature" => 8679.0)
    return compute_k_CCL2_sec_Steube1999_proxy(params, inputs, reference_values)
end


# Forward model (batch_accumulation)
function compute_k_CCL2_sec_bcproxy_yoshimura2023(params, inputs, reference_values)
    sec_rate = params["k_CCL2_sec"]
    cells = inputs["MDA_MB231_cell_count"]
    t_inc = inputs["MDA_MB231_time_interval_48h"]
    mw = reference_values["ccl2_molecular_weight_mature"]
    ucf = 0.041667
    vol = 1.0
    return sec_rate * cells * t_inc * mw * ucf / vol
end

function simulate_k_CCL2_sec_bcproxy_yoshimura2023(k_CCL2_sec)
    params = Dict("k_CCL2_sec" => k_CCL2_sec)
    inputs = Dict("MDA_MB231_CCL2_mass_48h" => 30.0, "MDA_MB231_time_interval_48h" => 48.0, "MDA_MB231_cell_count" => 1000000.0, "assumed_cv" => 0.5)
    reference_values = Dict("ccl2_molecular_weight_mature" => 8679.0)
    return compute_k_CCL2_sec_bcproxy_yoshimura2023(params, inputs, reference_values)
end


# Forward model (batch_accumulation)
function compute_k_CCL2_sec_psc_michalski2008(params, inputs, reference_values)
    sec_rate = params["k_CCL2_sec"]
    cells = inputs["psc_cell_seeded"]
    t_inc = inputs["incubation_time_48h"]
    mw = reference_values["ccl2_molecular_weight_mature"]
    ucf = 1000.0
    vol = inputs["medium_volume_well"]
    return sec_rate * cells * t_inc * mw * ucf / vol
end

function simulate_k_CCL2_sec_psc_michalski2008(k_CCL2_sec)
    params = Dict("k_CCL2_sec" => k_CCL2_sec)
    inputs = Dict("psc_cell_seeded" => 40000.0, "medium_volume_well" => 0.5, "incubation_time_48h" => 2.0, "mcp1_conc_48h_mean" => 200.0, "mcp1_conc_48h_cv_assumed" => 0.3)
    reference_values = Dict("ccl2_molecular_weight_mature" => 8679.0)
    return compute_k_CCL2_sec_psc_michalski2008(params, inputs, reference_values)
end


# Forward model (steady_state_concentration)
function compute_k_CCL2_sec_pdac_plasma_Nixon2013(params, inputs, reference_values)
    sec_rate = params["k_CCL2_sec"]
    ucf = 1.0
    source = reference_values["pdac_total_tumor_cells"]
    clearance = params["k_CCL2_deg"]
    vol = reference_values["blood_volume"]
    return sec_rate * ucf * source / (clearance * vol)
end

function simulate_k_CCL2_sec_pdac_plasma_Nixon2013(k_CCL2_sec, k_CCL2_deg)
    params = Dict("k_CCL2_sec" => k_CCL2_sec, "k_CCL2_deg" => k_CCL2_deg)
    inputs = Dict("mcp1_plasma_median_advanced_pdac" => 521.8, "mcp1_plasma_n_patients" => 328.0, "mcp1_plasma_assumed_cv" => 0.5, "mcp1_pgml_to_nmolL_factor" => 0.00011522064754003915)
    reference_values = Dict("blood_volume" => 5.0, "pdac_total_tumor_cells" => 1000000000.0)
    return compute_k_CCL2_sec_pdac_plasma_Nixon2013(params, inputs, reference_values)
end

function compute_k_M1_pol_Watkins2007_IL12_TAM_reprogramming(params, inputs)
    k = params["k_M1_pol"]
    t_half_days = log(2) / k
    return t_half_days  # days
end

function compute_k_M1_pol_repolarization_horhold2020(params, inputs)
    k = params["k_M1_pol"]
    t_half_days = log(2) / k
    return t_half_days  # days
end

function compute_k_M1_pol_rp182_m2_to_m1_repolarization(params::Dict, inputs::Dict)
    k = params["k_M1_pol"]
    # Stimulation time in days (stored directly in inputs)
    t = inputs["rp182_t_30min"]
    f0 = inputs["rp182_cd86pos_cd206pos_frac_vehicle"]
    frac = 1.0 - (1.0 - f0) * exp(-k * t)
    return frac
end


# Forward model (steady_state_ratio)
function compute_k_M1_pol_pdac_cd86_cd163_gu2023(params, inputs)
    r_num = params["k_M1_pol"]
    ucf = 1.0
    r_den = params["k_M2_pol"]
    d_num = 1.0
    d_den = 1.0
    return r_num * ucf * d_num / (r_den * d_den)
end

function simulate_k_M1_pol_pdac_cd86_cd163_gu2023(k_M1_pol, k_M2_pol)
    params = Dict("k_M1_pol" => k_M1_pol, "k_M2_pol" => k_M2_pol)
    inputs = Dict("cd86_primary_median_gu2023" => 11.6, "cd86_primary_min_gu2023" => 2.0, "cd86_primary_max_gu2023" => 31.2, "cd163_primary_median_gu2023" => 27.1, "cd163_primary_min_gu2023" => 7.6, "cd163_primary_max_gu2023" => 38.2, "n_primary_pdac_gu2023" => 42.0, "range_to_sd_factor_gu2023" => 4.0)
    return compute_k_M1_pol_pdac_cd86_cd163_gu2023(params, inputs)
end


# Forward model (steady_state_ratio)
function compute_k_M1_pol_steady_state_ratio_DLBCL2021(params, inputs)
    r_num = params["k_M1_pol"]
    ucf = 1.0
    r_den = params["k_M2_pol"]
    d_num = 1.0
    d_den = 1.0
    return r_num * ucf * d_num / (r_den * d_den)
end

function simulate_k_M1_pol_steady_state_ratio_DLBCL2021(k_M1_pol, k_M2_pol)
    params = Dict("k_M1_pol" => k_M1_pol, "k_M2_pol" => k_M2_pol)
    inputs = Dict("m1_fraction_mean" => 0.1574, "m1_fraction_sd" => 0.012, "m2_fraction_mean" => 0.211, "m2_fraction_sd" => 0.0476, "dlbcl_tam_n_patients" => 3.0)
    return compute_k_M1_pol_steady_state_ratio_DLBCL2021(params, inputs)
end


# Forward model (steady_state_ratio)
function compute_k_M1_pol_pdac_m1m2ratio_DeSimoni2023(params, inputs)
    r_num = params["k_M1_pol"]
    ucf = 1.0
    r_den = params["k_M2_pol"]
    d_num = 1.0
    d_den = 1.0
    return r_num * ucf * d_num / (r_den * d_den)
end

function simulate_k_M1_pol_pdac_m1m2ratio_DeSimoni2023(k_M1_pol, k_M2_pol)
    params = Dict("k_M1_pol" => k_M1_pol, "k_M2_pol" => k_M2_pol)
    inputs = Dict("inos_tumor_mean_per_hpf" => 5.0, "inos_normal_mean_per_hpf" => 2.5, "cd163_tumor_mean_per_hpf" => 92.0, "cd163_normal_mean_per_hpf" => 66.0, "n_patients_pdac_tme_desimoni2023" => 38.0, "m1_m2_ratio_assumed_cv" => 0.5)
    return compute_k_M1_pol_pdac_m1m2ratio_DeSimoni2023(params, inputs)
end


# Forward model (steady_state_ratio)
function compute_k_M1_pol_tam_ratio_herwig2013(params, inputs)
    r_num = params["k_M2_pol"]
    ucf = 1.0
    r_den = params["k_M1_pol"]
    d_num = 1.0
    d_den = 1.0
    return r_num * ucf * d_num / (r_den * d_den)
end

function simulate_k_M1_pol_tam_ratio_herwig2013(k_M1_pol, k_M2_pol)
    params = Dict("k_M1_pol" => k_M1_pol, "k_M2_pol" => k_M2_pol)
    inputs = Dict("tumor_m2_m1_ratio_mean" => 2.0, "tumor_m2_m1_ratio_cv" => 0.25)
    return compute_k_M1_pol_tam_ratio_herwig2013(params, inputs)
end

function compute_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015(params, inputs)
    k_rec = params["k_MDSC_rec"]
    cell_density = inputs["tumor_cell_density"]
    half_life = inputs["MDSC_half_life"]
    k_death = log(2) / half_life
    frac = k_rec / (k_death * cell_density) * 100.0
    return frac  # percent
end

function compute_k_MDSC_rec_oscc_ccl2_oo2022(params, inputs)
    k_rec = params["k_MDSC_rec"]
    V_eff = inputs["imaging_volume_per_field"]
    t_hours = inputs["migration_time_9h"]
    t_days = t_hours / 24.0
    migrated = k_rec * V_eff * t_days
    return migrated  # cells
end


# Forward model (steady_state_fraction)
function compute_k_MDSC_rec_PDAC_Porembka2012(params, inputs, reference_values)
    target_rate = params["k_MDSC_rec"]
    ucf = 1.0
    loss_rate = params["k_MDSC_death"]
    parent_density = reference_values["pdac_cd45_density_volumetric"]
    drive = 1.0
    return target_rate * ucf * drive / (loss_rate * parent_density)
end

function simulate_k_MDSC_rec_PDAC_Porembka2012(k_MDSC_rec, k_MDSC_death)
    params = Dict("k_MDSC_rec" => k_MDSC_rec, "k_MDSC_death" => k_MDSC_death)
    inputs = Dict("mdsc_frac_tumor_porembka_mean" => 0.666, "mdsc_frac_tumor_porembka_sd" => 0.032, "mdsc_frac_bm_porembka_mean" => 0.477, "mdsc_frac_tumor_kpc_mean" => 0.25, "gmdsc_frac_tumor_khaled_mean" => 0.1111, "mmdsc_frac_tumor_khaled_mean" => 0.0385)
    reference_values = Dict("pdac_cd45_density_volumetric" => 250000000.0)
    return compute_k_MDSC_rec_PDAC_Porembka2012(params, inputs, reference_values)
end

function compute_k_MDSC_rec_panc02_spleenexpansion_ghansah2013(params, inputs)
    # k_MDSC_rec: recruitment rate into the spleen surrogate compartment (cell/(milliliter*day))
    k_rec = params["k_MDSC_rec"]
    f0 = inputs["mdsc_fraction_baseline"]
    t = inputs["observation_time_day27"]
    rho = inputs["spleen_cell_density"]
    # Predicted MDSC fraction at time t assuming linear accumulation
    return f0 + (k_rec * t / rho)
end


# Forward model (steady_state_fraction)
function compute_k_MDSC_rec_pdac_trovato2019(params, inputs, reference_values)
    target_rate = params["k_MDSC_rec"]
    ucf = 1.0
    loss_rate = params["k_MDSC_death"]
    parent_density = reference_values["pdac_cd45_density_volumetric"]
    drive = 1.0
    return target_rate * ucf * drive / (loss_rate * parent_density)
end

function simulate_k_MDSC_rec_pdac_trovato2019(k_MDSC_rec, k_MDSC_death)
    params = Dict("k_MDSC_rec" => k_MDSC_rec, "k_MDSC_death" => k_MDSC_death)
    inputs = Dict("mmdsc_fraction_cd14_hdrlow_mean" => 0.969, "mmdsc_fraction_cd14_hdrlow_sd" => 0.167, "mmdsc_fraction_cd14_hdrlow_n" => 29.0)
    reference_values = Dict("pdac_cd45_density_volumetric" => 250000000.0)
    return compute_k_MDSC_rec_pdac_trovato2019(params, inputs, reference_values)
end


# Forward model (steady_state_fraction)
function compute_k_MDSC_rec_panc02_tnfr1_chopra2013(params, inputs, reference_values)
    target_rate = params["k_MDSC_rec"]
    ucf = 1.0
    loss_rate = params["k_MDSC_death"]
    parent_density = reference_values["pdac_cd45_density_volumetric"]
    drive = 1.0
    return target_rate * ucf * drive / (loss_rate * parent_density)
end

function simulate_k_MDSC_rec_panc02_tnfr1_chopra2013(k_MDSC_rec, k_MDSC_death)
    params = Dict("k_MDSC_rec" => k_MDSC_rec, "k_MDSC_death" => k_MDSC_death)
    inputs = Dict("mdsc_fraction_panc02_pancreas_mean" => 0.1717, "mdsc_fraction_panc02_pancreas_sem" => 0.0702, "n_panc02_pancreas_wt_tumors" => 4.0)
    reference_values = Dict("pdac_cd45_density_volumetric" => 250000000.0)
    return compute_k_MDSC_rec_panc02_tnfr1_chopra2013(params, inputs, reference_values)
end


# Forward model (steady_state_density)
function compute_k_Mac_rec_PDAC_M1_recruitment_Gu2023(params, inputs, reference_values)
    target_rate = params["k_Mac_rec"]
    ucf = 1.0
    source_pool = 1.0
    loss_rate = params["k_Mac_death"]
    section_vol = reference_values["ihc_section_volume_4um"]
    eff = 1.0
    excl = 0.0
    return target_rate * ucf * source_pool * eff * (1 - excl) / loss_rate * section_vol
end

function simulate_k_Mac_rec_PDAC_M1_recruitment_Gu2023(k_Mac_rec, k_Mac_death)
    params = Dict("k_Mac_rec" => k_Mac_rec, "k_Mac_death" => k_Mac_death)
    inputs = Dict("M1_per_HPF_primary_PDAC" => 11.6, "M1_per_HPF_range_low" => 2.0, "M1_per_HPF_range_high" => 31.2, "section_thickness_histology" => 4.0, "HPF_area_400x_microscope" => 0.196)
    reference_values = Dict("ihc_section_volume_4um" => 4e-06)
    return compute_k_Mac_rec_PDAC_M1_recruitment_Gu2023(params, inputs, reference_values)
end


# Forward model (steady_state_density)
function compute_k_Mac_rec_PDAC_TAM_recruitment_Chen2015(params, inputs, reference_values)
    target_rate = params["k_Mac_rec"]
    ucf = 1.0
    source_pool = 1.0
    loss_rate = params["k_Mac_death"]
    section_vol = reference_values["ihc_section_volume_3um"]
    eff = 1.0
    excl = 0.0
    return target_rate * ucf * source_pool * eff * (1 - excl) / loss_rate * section_vol
end

function simulate_k_Mac_rec_PDAC_TAM_recruitment_Chen2015(k_Mac_rec, k_Mac_death)
    params = Dict("k_Mac_rec" => k_Mac_rec, "k_Mac_death" => k_Mac_death)
    inputs = Dict("cd68_peri_median_per_hpf" => 71.5, "cd68_peri_range_low_per_hpf" => 13.0, "cd68_peri_range_high_per_hpf" => 198.0, "section_thickness_um" => 3.0, "hpf_area_mm2" => 0.237, "macrophage_res_time_days" => 30.0, "H_CCL2_PD" => 1.0)
    reference_values = Dict("ihc_section_volume_3um" => 3e-06)
    return compute_k_Mac_rec_PDAC_TAM_recruitment_Chen2015(params, inputs, reference_values)
end


# Forward model (steady_state_ratio)
function compute_k_Mac_rec_humanPDAC_CD40_2021(params, inputs)
    r_num = params["k_M2_pol"]
    ucf = 1.0
    r_den = params["k_M1_pol"]
    d_num = 1.0
    d_den = 1.0
    return r_num * ucf * d_num / (r_den * d_den)
end

function simulate_k_Mac_rec_humanPDAC_CD40_2021(k_M2_pol, k_M1_pol)
    params = Dict("k_M2_pol" => k_M2_pol, "k_M1_pol" => k_M1_pol)
    inputs = Dict("cd68_pixels_mean" => 21865.0, "cd163_pixels_mean" => 7553.0, "hladr_pixels_mean" => 4823.0, "n_patients_cd40" => 12.0, "assumed_cv_m2m1_ratio" => 0.3)
    return compute_k_Mac_rec_humanPDAC_CD40_2021(params, inputs)
end


# Analytical solution for first-order decay: du/dt = -k*u => u(t) = u₀ * exp(-k*t)
function simulate_k_apsc_death_melatoninPSC_Estaras2021(k_apsc_death)
    d = DATA["k_apsc_death_melatoninPSC_Estaras2021"]
    t_final = d.t_span[2]
    y0 = d.y0[1]
    return y0 * exp(-k_apsc_death * t_final)
end

function compute_k_apsc_death_RA_Xiao2015(params, inputs)
    k = params["k_apsc_death"]
    t_half = log(2) / k
    return t_half  # days
end


# Analytical solution for first-order decay: du/dt = -k*u => u(t) = u₀ * exp(-k*t)
function simulate_k_apsc_death_hsc_apoptosis_issa2001(k_apsc_death)
    d = DATA["k_apsc_death_hsc_apoptosis_issa2001"]
    t_final = d.t_span[2]
    y0 = d.y0[1]
    return y0 * exp(-k_apsc_death * t_final)
end

function compute_k_psc_activation_apte1998(params, inputs)
    k = params["k_psc_activation"]
    t_days = 1.0 / k
    t_hours = t_days * 24.0
    return t_hours  # hours
end

function compute_n_CD8_clones_Meng2023_PDAC(params, inputs)
    n_clones = params["n_CD8_clones"]
    n_tumors = inputs["n_PDAC_tumors_Meng2023"]
    total_tr = n_clones * n_tumors
    return total_tr
end

function compute_q_CD8_T_in_extravasation_boissonnas2007(params, inputs)
    q = params["q_CD8_T_in"]
    CD8_C = inputs["OT1_injected"]
    t_half_h = inputs["CD8_eff_half_life"]
    k_death = log(2) / (t_half_h * 60.0)
    thickness_mm = inputs["section_thickness_um"] / 1000.0
    rho = q * CD8_C / k_death / 1000.0
    d_2d = rho * thickness_mm
    return d_2d  # cells/mm^2
end

function compute_q_CD8_T_in_yorty2007_sv11_brain_tumor(params, inputs)
    q = params["q_CD8_T_in"]
    V_ref = inputs["reference_tumor_volume"]
    k_in_per_min = q * V_ref
    t_peak_min = 3.0 / k_in_per_min
    t_peak_days = t_peak_min / (24.0 * 60.0)
    return t_peak_days  # days
end


# Forward model (steady_state_density)
function compute_q_CD8_T_in_PDAC_CD8density_ModPathol2019(params, inputs, reference_values)
    target_rate = params["q_CD8_T_in"]
    ucf = 1440.0
    source_pool = reference_values["circulating_cd8_count"]
    loss_rate = params["k_CD8_death"]
    section_vol = reference_values["ihc_section_volume_4um"]
    eff = 1.0
    excl = params["cd8_exclusion_fraction"]
    return target_rate * ucf * source_pool * eff * (1 - excl) / loss_rate * section_vol
end

function simulate_q_CD8_T_in_PDAC_CD8density_ModPathol2019(q_CD8_T_in, k_CD8_death, cd8_exclusion_fraction)
    params = Dict("q_CD8_T_in" => q_CD8_T_in, "k_CD8_death" => k_CD8_death, "cd8_exclusion_fraction" => cd8_exclusion_fraction)
    inputs = Dict("pdac_cd8_center_mean" => 166.9, "pdac_cd8_center_q1" => 66.0, "pdac_cd8_center_q3" => 200.2, "pdac_cd8_center_n" => 214.0, "iqr_to_sd_factor" => 1.349, "cd8_exclusion_fraction" => 0.9, "crc_cd8_core_median" => 96.0, "crc_cd8_margin_median" => 262.0, "melanoma_cd8_high_cutoff" => 222.9)
    reference_values = Dict("circulating_cd8_count" => 2000000000.0, "ihc_section_volume_4um" => 4e-06)
    return compute_q_CD8_T_in_PDAC_CD8density_ModPathol2019(params, inputs, reference_values)
end

function compute_q_Treg_T_in_Tremblay2017_MRIcelltracking(params, inputs)
    q = params["q_Treg_T_in"]
    V_ref = inputs["V_T_ref"]
    k_extrav_per_min = q * V_ref
    t_half_min = log(2) / k_extrav_per_min
    t_half_h = t_half_min / 60.0
    return t_half_h  # hours
end

function compute_q_Treg_T_in_PDAC_Tang2014(params, inputs)
    q = params["q_Treg_T_in"]
    t_doubling = inputs["Treg_doubling_time_mean"]
    k_per_day = log(2) / t_doubling
    k_per_min = k_per_day / (24.0 * 60.0)
    V_ref = 1.0
    ratio = q * V_ref / k_per_min
    return ratio
end

function compute_q_Treg_T_in_extravasation_PDAC(params, inputs)
    q = params["q_Treg_T_in"]
    tau_hr = inputs["migration_time_4h_hr"]
    tau_min = tau_hr * 60.0
    V_T_ref = 1.0
    k_in = q * V_T_ref
    f_treg = 1.0 - exp(-k_in * tau_min)
    return f_treg
end


# Forward model (steady_state_density)
function compute_q_Treg_T_in_Jiang2014_Liyanage2002(params, inputs, reference_values)
    target_rate = params["q_Treg_T_in"]
    ucf = 1440.0
    source_pool = reference_values["circulating_treg_count_pdac"]
    loss_rate = params["k_Treg_death"]
    section_vol = reference_values["ihc_section_volume_5um"]
    eff = 1.0
    excl = 0.0
    return target_rate * ucf * source_pool * eff * (1 - excl) / loss_rate * section_vol
end

function simulate_q_Treg_T_in_Jiang2014_Liyanage2002(q_Treg_T_in, k_Treg_death)
    params = Dict("q_Treg_T_in" => q_Treg_T_in, "k_Treg_death" => k_Treg_death)
    inputs = Dict("foxp3_density_tumor_mean_per_hpf" => 4.8, "foxp3_density_tumor_sd_per_hpf" => 5.2, "section_thickness" => 0.0005, "hpf_area" => 0.000625, "treg_fraction_pbmc_pancreas_mean" => 0.132, "treg_fraction_pbmc_pancreas_se" => 0.0113, "cd4_abs_count_mean" => 1039990.0, "cd4_abs_count_sd" => 338020.0)
    reference_values = Dict("circulating_treg_count_pdac" => 686400000.0, "ihc_section_volume_5um" => 5e-06)
    return compute_q_Treg_T_in_Jiang2014_Liyanage2002(params, inputs, reference_values)
end


# ======================================================================
# JOINT TURING MODEL
# ======================================================================
@model function joint_calibration(data)
    # =========================================
    # PRIORS (shared across targets)
    # =========================================
    N_IL2_CD4 ~ Normal(8.0, 2.0)  # Used by: N_IL2_CD4_division_destiny_Gett1998
    N_IL2_CD8 ~ Normal(5.0, 2.0)  # Used by: N_IL2_CD8_division_generations_castro2012
    k_C1_growth ~ LogNormal(-5.0, 1.0)  # Used by: k_C1_growth_pdac_human_vdt_ahn2017, k_C1_growth_pdac_tumor_doubling_jang2015
    k_CCL2_sec ~ LogNormal(-20.64, 2.5)  # Used by: k_CCL2_sec_Fujita2010_PrSC, k_CCL2_sec_Steube1999_proxy, k_CCL2_sec_bcproxy_yoshimura2023, k_CCL2_sec_psc_michalski2008, k_CCL2_sec_pdac_plasma_Nixon2013
    k_CCL2_deg ~ LogNormal(1.94, 0.3)  # Used by: k_CCL2_sec_pdac_plasma_Nixon2013
    k_M1_pol ~ LogNormal(0.0, 3.4)  # Used by: k_M1_pol_Watkins2007_IL12_TAM_reprogramming, k_M1_pol_repolarization_horhold2020, k_M1_pol_rp182_m2_to_m1_repolarization, k_M1_pol_pdac_cd86_cd163_gu2023, k_M1_pol_steady_state_ratio_DLBCL2021, k_M1_pol_pdac_m1m2ratio_DeSimoni2023, k_M1_pol_tam_ratio_herwig2013, k_Mac_rec_humanPDAC_CD40_2021
    k_M2_pol ~ LogNormal(0.0, 3.4)  # Used by: k_M1_pol_pdac_cd86_cd163_gu2023, k_M1_pol_steady_state_ratio_DLBCL2021, k_M1_pol_pdac_m1m2ratio_DeSimoni2023, k_M1_pol_tam_ratio_herwig2013, k_Mac_rec_humanPDAC_CD40_2021
    k_MDSC_rec ~ LogNormal(17.44, 2.5)  # Used by: k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015, k_MDSC_rec_oscc_ccl2_oo2022, k_MDSC_rec_PDAC_Porembka2012, k_MDSC_rec_panc02_spleenexpansion_ghansah2013, k_MDSC_rec_pdac_trovato2019, k_MDSC_rec_panc02_tnfr1_chopra2013
    k_MDSC_death ~ LogNormal(0.0, 1.5)  # Used by: k_MDSC_rec_PDAC_Porembka2012, k_MDSC_rec_pdac_trovato2019, k_MDSC_rec_panc02_tnfr1_chopra2013
    k_Mac_rec ~ LogNormal(13.89, 1.5)  # Used by: k_Mac_rec_PDAC_M1_recruitment_Gu2023, k_Mac_rec_PDAC_TAM_recruitment_Chen2015
    k_Mac_death ~ LogNormal(-3.91, 1.0)  # Used by: k_Mac_rec_PDAC_M1_recruitment_Gu2023, k_Mac_rec_PDAC_TAM_recruitment_Chen2015
    k_apsc_death ~ LogNormal(-2.65, 1.7)  # Used by: k_apsc_death_melatoninPSC_Estaras2021, k_apsc_death_RA_Xiao2015, k_apsc_death_hsc_apoptosis_issa2001
    k_psc_activation ~ LogNormal(-0.693, 1.0)  # Used by: k_psc_activation_apte1998
    n_CD8_clones ~ LogNormal(2.3, 1.0)  # Used by: n_CD8_clones_Meng2023_PDAC
    q_CD8_T_in ~ LogNormal(-8.0, 3.4)  # Used by: q_CD8_T_in_extravasation_boissonnas2007, q_CD8_T_in_yorty2007_sv11_brain_tumor, q_CD8_T_in_PDAC_CD8density_ModPathol2019
    k_CD8_death ~ LogNormal(0.0, 1.0)  # Used by: q_CD8_T_in_PDAC_CD8density_ModPathol2019
    cd8_exclusion_fraction ~ Uniform(0.7, 0.99)  # Used by: q_CD8_T_in_PDAC_CD8density_ModPathol2019
    q_Treg_T_in ~ LogNormal(-7.0, 2.0)  # Used by: q_Treg_T_in_Tremblay2017_MRIcelltracking, q_Treg_T_in_PDAC_Tang2014, q_Treg_T_in_extravasation_PDAC, q_Treg_T_in_Jiang2014_Liyanage2002
    k_Treg_death ~ LogNormal(-2.3, 1.0)  # Used by: q_Treg_T_in_Jiang2014_Liyanage2002

    # =========================================
    # LIKELIHOODS
    # =========================================

    # N_IL2_CD4_division_destiny_Gett1998
    params_N_IL2_CD4_division_destiny_Gett1998 = Dict("N_IL2_CD4" => N_IL2_CD4)
    inputs_N_IL2_CD4_division_destiny_Gett1998 = data["N_IL2_CD4_division_destiny_Gett1998"].inputs
    pred_N_IL2_CD4_division_destiny_Gett1998 = compute_N_IL2_CD4_division_destiny_Gett1998(params_N_IL2_CD4_division_destiny_Gett1998, inputs_N_IL2_CD4_division_destiny_Gett1998)
    data["N_IL2_CD4_division_destiny_Gett1998"].obs_median[1] ~ Normal(pred_N_IL2_CD4_division_destiny_Gett1998, data["N_IL2_CD4_division_destiny_Gett1998"].obs_sigma[1])

    # N_IL2_CD8_division_generations_castro2012
    params_N_IL2_CD8_division_generations_castro2012 = Dict("N_IL2_CD8" => N_IL2_CD8)
    inputs_N_IL2_CD8_division_generations_castro2012 = data["N_IL2_CD8_division_generations_castro2012"].inputs
    pred_N_IL2_CD8_division_generations_castro2012 = compute_N_IL2_CD8_division_generations_castro2012(params_N_IL2_CD8_division_generations_castro2012, inputs_N_IL2_CD8_division_generations_castro2012)
    data["N_IL2_CD8_division_generations_castro2012"].obs_median[1] ~ Normal(pred_N_IL2_CD8_division_generations_castro2012, data["N_IL2_CD8_division_generations_castro2012"].obs_sigma[1])
    data["N_IL2_CD8_division_generations_castro2012"].obs_median[2] ~ Normal(pred_N_IL2_CD8_division_generations_castro2012, data["N_IL2_CD8_division_generations_castro2012"].obs_sigma[2])

    # k_C1_growth_pdac_human_vdt_ahn2017
    params_k_C1_growth_pdac_human_vdt_ahn2017 = Dict("k_C1_growth" => k_C1_growth)
    inputs_k_C1_growth_pdac_human_vdt_ahn2017 = data["k_C1_growth_pdac_human_vdt_ahn2017"].inputs
    pred_k_C1_growth_pdac_human_vdt_ahn2017 = compute_k_C1_growth_pdac_human_vdt_ahn2017(params_k_C1_growth_pdac_human_vdt_ahn2017, inputs_k_C1_growth_pdac_human_vdt_ahn2017)
    data["k_C1_growth_pdac_human_vdt_ahn2017"].obs_median[1] ~ LogNormal(log(pred_k_C1_growth_pdac_human_vdt_ahn2017), data["k_C1_growth_pdac_human_vdt_ahn2017"].obs_sigma[1])

    # k_C1_growth_pdac_tumor_doubling_jang2015
    params_k_C1_growth_pdac_tumor_doubling_jang2015 = Dict("k_C1_growth" => k_C1_growth)
    inputs_k_C1_growth_pdac_tumor_doubling_jang2015 = data["k_C1_growth_pdac_tumor_doubling_jang2015"].inputs
    pred_k_C1_growth_pdac_tumor_doubling_jang2015 = compute_k_C1_growth_pdac_tumor_doubling_jang2015(params_k_C1_growth_pdac_tumor_doubling_jang2015, inputs_k_C1_growth_pdac_tumor_doubling_jang2015)
    data["k_C1_growth_pdac_tumor_doubling_jang2015"].obs_median[1] ~ LogNormal(log(pred_k_C1_growth_pdac_tumor_doubling_jang2015), data["k_C1_growth_pdac_tumor_doubling_jang2015"].obs_sigma[1])

    # k_CCL2_sec_Fujita2010_PrSC
    pred_k_CCL2_sec_Fujita2010_PrSC = simulate_k_CCL2_sec_Fujita2010_PrSC(k_CCL2_sec)
    data["k_CCL2_sec_Fujita2010_PrSC"].obs_median[1] ~ LogNormal(log(pred_k_CCL2_sec_Fujita2010_PrSC), data["k_CCL2_sec_Fujita2010_PrSC"].obs_sigma[1])

    # k_CCL2_sec_Steube1999_proxy
    pred_k_CCL2_sec_Steube1999_proxy = simulate_k_CCL2_sec_Steube1999_proxy(k_CCL2_sec)
    data["k_CCL2_sec_Steube1999_proxy"].obs_median[1] ~ LogNormal(log(pred_k_CCL2_sec_Steube1999_proxy), data["k_CCL2_sec_Steube1999_proxy"].obs_sigma[1])

    # k_CCL2_sec_bcproxy_yoshimura2023
    pred_k_CCL2_sec_bcproxy_yoshimura2023 = simulate_k_CCL2_sec_bcproxy_yoshimura2023(k_CCL2_sec)
    data["k_CCL2_sec_bcproxy_yoshimura2023"].obs_median[1] ~ LogNormal(log(pred_k_CCL2_sec_bcproxy_yoshimura2023), data["k_CCL2_sec_bcproxy_yoshimura2023"].obs_sigma[1])

    # k_CCL2_sec_psc_michalski2008
    pred_k_CCL2_sec_psc_michalski2008 = simulate_k_CCL2_sec_psc_michalski2008(k_CCL2_sec)
    data["k_CCL2_sec_psc_michalski2008"].obs_median[1] ~ LogNormal(log(pred_k_CCL2_sec_psc_michalski2008), data["k_CCL2_sec_psc_michalski2008"].obs_sigma[1])

    # k_CCL2_sec_pdac_plasma_Nixon2013
    pred_k_CCL2_sec_pdac_plasma_Nixon2013 = simulate_k_CCL2_sec_pdac_plasma_Nixon2013(k_CCL2_sec, k_CCL2_deg)
    data["k_CCL2_sec_pdac_plasma_Nixon2013"].obs_median[1] ~ LogNormal(log(pred_k_CCL2_sec_pdac_plasma_Nixon2013), data["k_CCL2_sec_pdac_plasma_Nixon2013"].obs_sigma[1])

    # k_M1_pol_Watkins2007_IL12_TAM_reprogramming
    params_k_M1_pol_Watkins2007_IL12_TAM_reprogramming = Dict("k_M1_pol" => k_M1_pol)
    inputs_k_M1_pol_Watkins2007_IL12_TAM_reprogramming = data["k_M1_pol_Watkins2007_IL12_TAM_reprogramming"].inputs
    pred_k_M1_pol_Watkins2007_IL12_TAM_reprogramming = compute_k_M1_pol_Watkins2007_IL12_TAM_reprogramming(params_k_M1_pol_Watkins2007_IL12_TAM_reprogramming, inputs_k_M1_pol_Watkins2007_IL12_TAM_reprogramming)
    data["k_M1_pol_Watkins2007_IL12_TAM_reprogramming"].obs_median[1] ~ LogNormal(log(pred_k_M1_pol_Watkins2007_IL12_TAM_reprogramming), data["k_M1_pol_Watkins2007_IL12_TAM_reprogramming"].obs_sigma[1])

    # k_M1_pol_repolarization_horhold2020
    params_k_M1_pol_repolarization_horhold2020 = Dict("k_M1_pol" => k_M1_pol)
    inputs_k_M1_pol_repolarization_horhold2020 = data["k_M1_pol_repolarization_horhold2020"].inputs
    pred_k_M1_pol_repolarization_horhold2020 = compute_k_M1_pol_repolarization_horhold2020(params_k_M1_pol_repolarization_horhold2020, inputs_k_M1_pol_repolarization_horhold2020)
    data["k_M1_pol_repolarization_horhold2020"].obs_median[1] ~ LogNormal(log(pred_k_M1_pol_repolarization_horhold2020), data["k_M1_pol_repolarization_horhold2020"].obs_sigma[1])

    # k_M1_pol_rp182_m2_to_m1_repolarization
    params_k_M1_pol_rp182_m2_to_m1_repolarization = Dict("k_M1_pol" => k_M1_pol)
    inputs_k_M1_pol_rp182_m2_to_m1_repolarization = data["k_M1_pol_rp182_m2_to_m1_repolarization"].inputs
    pred_k_M1_pol_rp182_m2_to_m1_repolarization = compute_k_M1_pol_rp182_m2_to_m1_repolarization(params_k_M1_pol_rp182_m2_to_m1_repolarization, inputs_k_M1_pol_rp182_m2_to_m1_repolarization)
    data["k_M1_pol_rp182_m2_to_m1_repolarization"].obs_median[1] ~ Normal(pred_k_M1_pol_rp182_m2_to_m1_repolarization, data["k_M1_pol_rp182_m2_to_m1_repolarization"].obs_sigma[1])

    # k_M1_pol_pdac_cd86_cd163_gu2023
    pred_k_M1_pol_pdac_cd86_cd163_gu2023 = simulate_k_M1_pol_pdac_cd86_cd163_gu2023(k_M1_pol, k_M2_pol)
    data["k_M1_pol_pdac_cd86_cd163_gu2023"].obs_median[1] ~ LogNormal(log(pred_k_M1_pol_pdac_cd86_cd163_gu2023), data["k_M1_pol_pdac_cd86_cd163_gu2023"].obs_sigma[1])

    # k_M1_pol_steady_state_ratio_DLBCL2021
    pred_k_M1_pol_steady_state_ratio_DLBCL2021 = simulate_k_M1_pol_steady_state_ratio_DLBCL2021(k_M1_pol, k_M2_pol)
    data["k_M1_pol_steady_state_ratio_DLBCL2021"].obs_median[1] ~ LogNormal(log(pred_k_M1_pol_steady_state_ratio_DLBCL2021), data["k_M1_pol_steady_state_ratio_DLBCL2021"].obs_sigma[1])

    # k_M1_pol_pdac_m1m2ratio_DeSimoni2023
    pred_k_M1_pol_pdac_m1m2ratio_DeSimoni2023 = simulate_k_M1_pol_pdac_m1m2ratio_DeSimoni2023(k_M1_pol, k_M2_pol)
    data["k_M1_pol_pdac_m1m2ratio_DeSimoni2023"].obs_median[1] ~ LogNormal(log(pred_k_M1_pol_pdac_m1m2ratio_DeSimoni2023), data["k_M1_pol_pdac_m1m2ratio_DeSimoni2023"].obs_sigma[1])

    # k_M1_pol_tam_ratio_herwig2013
    pred_k_M1_pol_tam_ratio_herwig2013 = simulate_k_M1_pol_tam_ratio_herwig2013(k_M1_pol, k_M2_pol)
    data["k_M1_pol_tam_ratio_herwig2013"].obs_median[1] ~ LogNormal(log(pred_k_M1_pol_tam_ratio_herwig2013), data["k_M1_pol_tam_ratio_herwig2013"].obs_sigma[1])

    # k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015
    params_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015 = Dict("k_MDSC_rec" => k_MDSC_rec)
    inputs_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015 = data["k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015"].inputs
    pred_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015 = compute_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015(params_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015, inputs_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015)
    data["k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015"].obs_median[1] ~ LogNormal(log(pred_k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015), data["k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015"].obs_sigma[1])

    # k_MDSC_rec_oscc_ccl2_oo2022
    params_k_MDSC_rec_oscc_ccl2_oo2022 = Dict("k_MDSC_rec" => k_MDSC_rec)
    inputs_k_MDSC_rec_oscc_ccl2_oo2022 = data["k_MDSC_rec_oscc_ccl2_oo2022"].inputs
    pred_k_MDSC_rec_oscc_ccl2_oo2022 = compute_k_MDSC_rec_oscc_ccl2_oo2022(params_k_MDSC_rec_oscc_ccl2_oo2022, inputs_k_MDSC_rec_oscc_ccl2_oo2022)
    data["k_MDSC_rec_oscc_ccl2_oo2022"].obs_median[1] ~ LogNormal(log(pred_k_MDSC_rec_oscc_ccl2_oo2022), data["k_MDSC_rec_oscc_ccl2_oo2022"].obs_sigma[1])

    # k_MDSC_rec_PDAC_Porembka2012
    pred_k_MDSC_rec_PDAC_Porembka2012 = simulate_k_MDSC_rec_PDAC_Porembka2012(k_MDSC_rec, k_MDSC_death)
    data["k_MDSC_rec_PDAC_Porembka2012"].obs_median[1] ~ Normal(pred_k_MDSC_rec_PDAC_Porembka2012, data["k_MDSC_rec_PDAC_Porembka2012"].obs_sigma[1])

    # k_MDSC_rec_panc02_spleenexpansion_ghansah2013
    params_k_MDSC_rec_panc02_spleenexpansion_ghansah2013 = Dict("k_MDSC_rec" => k_MDSC_rec)
    inputs_k_MDSC_rec_panc02_spleenexpansion_ghansah2013 = data["k_MDSC_rec_panc02_spleenexpansion_ghansah2013"].inputs
    pred_k_MDSC_rec_panc02_spleenexpansion_ghansah2013 = compute_k_MDSC_rec_panc02_spleenexpansion_ghansah2013(params_k_MDSC_rec_panc02_spleenexpansion_ghansah2013, inputs_k_MDSC_rec_panc02_spleenexpansion_ghansah2013)
    data["k_MDSC_rec_panc02_spleenexpansion_ghansah2013"].obs_median[1] ~ LogNormal(log(pred_k_MDSC_rec_panc02_spleenexpansion_ghansah2013), data["k_MDSC_rec_panc02_spleenexpansion_ghansah2013"].obs_sigma[1])

    # k_MDSC_rec_pdac_trovato2019
    pred_k_MDSC_rec_pdac_trovato2019 = simulate_k_MDSC_rec_pdac_trovato2019(k_MDSC_rec, k_MDSC_death)
    data["k_MDSC_rec_pdac_trovato2019"].obs_median[1] ~ LogNormal(log(pred_k_MDSC_rec_pdac_trovato2019), data["k_MDSC_rec_pdac_trovato2019"].obs_sigma[1])

    # k_MDSC_rec_panc02_tnfr1_chopra2013
    pred_k_MDSC_rec_panc02_tnfr1_chopra2013 = simulate_k_MDSC_rec_panc02_tnfr1_chopra2013(k_MDSC_rec, k_MDSC_death)
    data["k_MDSC_rec_panc02_tnfr1_chopra2013"].obs_median[1] ~ LogNormal(log(pred_k_MDSC_rec_panc02_tnfr1_chopra2013), data["k_MDSC_rec_panc02_tnfr1_chopra2013"].obs_sigma[1])

    # k_Mac_rec_PDAC_M1_recruitment_Gu2023
    pred_k_Mac_rec_PDAC_M1_recruitment_Gu2023 = simulate_k_Mac_rec_PDAC_M1_recruitment_Gu2023(k_Mac_rec, k_Mac_death)
    data["k_Mac_rec_PDAC_M1_recruitment_Gu2023"].obs_median[1] ~ LogNormal(log(pred_k_Mac_rec_PDAC_M1_recruitment_Gu2023), data["k_Mac_rec_PDAC_M1_recruitment_Gu2023"].obs_sigma[1])

    # k_Mac_rec_PDAC_TAM_recruitment_Chen2015
    pred_k_Mac_rec_PDAC_TAM_recruitment_Chen2015 = simulate_k_Mac_rec_PDAC_TAM_recruitment_Chen2015(k_Mac_rec, k_Mac_death)
    data["k_Mac_rec_PDAC_TAM_recruitment_Chen2015"].obs_median[1] ~ LogNormal(log(pred_k_Mac_rec_PDAC_TAM_recruitment_Chen2015), data["k_Mac_rec_PDAC_TAM_recruitment_Chen2015"].obs_sigma[1])

    # k_Mac_rec_humanPDAC_CD40_2021
    pred_k_Mac_rec_humanPDAC_CD40_2021 = simulate_k_Mac_rec_humanPDAC_CD40_2021(k_M2_pol, k_M1_pol)
    data["k_Mac_rec_humanPDAC_CD40_2021"].obs_median[1] ~ LogNormal(log(pred_k_Mac_rec_humanPDAC_CD40_2021), data["k_Mac_rec_humanPDAC_CD40_2021"].obs_sigma[1])

    # k_apsc_death_melatoninPSC_Estaras2021
    pred_k_apsc_death_melatoninPSC_Estaras2021 = simulate_k_apsc_death_melatoninPSC_Estaras2021(k_apsc_death)
    data["k_apsc_death_melatoninPSC_Estaras2021"].obs_median[1] ~ Normal(pred_k_apsc_death_melatoninPSC_Estaras2021, data["k_apsc_death_melatoninPSC_Estaras2021"].obs_sigma[1])

    # k_apsc_death_RA_Xiao2015
    params_k_apsc_death_RA_Xiao2015 = Dict("k_apsc_death" => k_apsc_death)
    inputs_k_apsc_death_RA_Xiao2015 = data["k_apsc_death_RA_Xiao2015"].inputs
    pred_k_apsc_death_RA_Xiao2015 = compute_k_apsc_death_RA_Xiao2015(params_k_apsc_death_RA_Xiao2015, inputs_k_apsc_death_RA_Xiao2015)
    data["k_apsc_death_RA_Xiao2015"].obs_median[1] ~ LogNormal(log(pred_k_apsc_death_RA_Xiao2015), data["k_apsc_death_RA_Xiao2015"].obs_sigma[1])

    # k_apsc_death_hsc_apoptosis_issa2001
    pred_k_apsc_death_hsc_apoptosis_issa2001 = simulate_k_apsc_death_hsc_apoptosis_issa2001(k_apsc_death)
    data["k_apsc_death_hsc_apoptosis_issa2001"].obs_median[1] ~ LogNormal(log(pred_k_apsc_death_hsc_apoptosis_issa2001), data["k_apsc_death_hsc_apoptosis_issa2001"].obs_sigma[1])

    # k_psc_activation_apte1998
    params_k_psc_activation_apte1998 = Dict("k_psc_activation" => k_psc_activation)
    inputs_k_psc_activation_apte1998 = data["k_psc_activation_apte1998"].inputs
    pred_k_psc_activation_apte1998 = compute_k_psc_activation_apte1998(params_k_psc_activation_apte1998, inputs_k_psc_activation_apte1998)
    data["k_psc_activation_apte1998"].obs_median[1] ~ LogNormal(log(pred_k_psc_activation_apte1998), data["k_psc_activation_apte1998"].obs_sigma[1])

    # n_CD8_clones_Meng2023_PDAC
    params_n_CD8_clones_Meng2023_PDAC = Dict("n_CD8_clones" => n_CD8_clones)
    inputs_n_CD8_clones_Meng2023_PDAC = data["n_CD8_clones_Meng2023_PDAC"].inputs
    pred_n_CD8_clones_Meng2023_PDAC = compute_n_CD8_clones_Meng2023_PDAC(params_n_CD8_clones_Meng2023_PDAC, inputs_n_CD8_clones_Meng2023_PDAC)
    data["n_CD8_clones_Meng2023_PDAC"].obs_median[1] ~ LogNormal(log(pred_n_CD8_clones_Meng2023_PDAC), data["n_CD8_clones_Meng2023_PDAC"].obs_sigma[1])

    # q_CD8_T_in_extravasation_boissonnas2007
    params_q_CD8_T_in_extravasation_boissonnas2007 = Dict("q_CD8_T_in" => q_CD8_T_in)
    inputs_q_CD8_T_in_extravasation_boissonnas2007 = data["q_CD8_T_in_extravasation_boissonnas2007"].inputs
    pred_q_CD8_T_in_extravasation_boissonnas2007 = compute_q_CD8_T_in_extravasation_boissonnas2007(params_q_CD8_T_in_extravasation_boissonnas2007, inputs_q_CD8_T_in_extravasation_boissonnas2007)
    data["q_CD8_T_in_extravasation_boissonnas2007"].obs_median[1] ~ LogNormal(log(pred_q_CD8_T_in_extravasation_boissonnas2007), data["q_CD8_T_in_extravasation_boissonnas2007"].obs_sigma[1])

    # q_CD8_T_in_yorty2007_sv11_brain_tumor
    params_q_CD8_T_in_yorty2007_sv11_brain_tumor = Dict("q_CD8_T_in" => q_CD8_T_in)
    inputs_q_CD8_T_in_yorty2007_sv11_brain_tumor = data["q_CD8_T_in_yorty2007_sv11_brain_tumor"].inputs
    pred_q_CD8_T_in_yorty2007_sv11_brain_tumor = compute_q_CD8_T_in_yorty2007_sv11_brain_tumor(params_q_CD8_T_in_yorty2007_sv11_brain_tumor, inputs_q_CD8_T_in_yorty2007_sv11_brain_tumor)
    data["q_CD8_T_in_yorty2007_sv11_brain_tumor"].obs_median[1] ~ LogNormal(log(pred_q_CD8_T_in_yorty2007_sv11_brain_tumor), data["q_CD8_T_in_yorty2007_sv11_brain_tumor"].obs_sigma[1])

    # q_CD8_T_in_PDAC_CD8density_ModPathol2019
    pred_q_CD8_T_in_PDAC_CD8density_ModPathol2019 = simulate_q_CD8_T_in_PDAC_CD8density_ModPathol2019(q_CD8_T_in, k_CD8_death, cd8_exclusion_fraction)
    data["q_CD8_T_in_PDAC_CD8density_ModPathol2019"].obs_median[1] ~ LogNormal(log(pred_q_CD8_T_in_PDAC_CD8density_ModPathol2019), data["q_CD8_T_in_PDAC_CD8density_ModPathol2019"].obs_sigma[1])

    # q_Treg_T_in_Tremblay2017_MRIcelltracking
    params_q_Treg_T_in_Tremblay2017_MRIcelltracking = Dict("q_Treg_T_in" => q_Treg_T_in)
    inputs_q_Treg_T_in_Tremblay2017_MRIcelltracking = data["q_Treg_T_in_Tremblay2017_MRIcelltracking"].inputs
    pred_q_Treg_T_in_Tremblay2017_MRIcelltracking = compute_q_Treg_T_in_Tremblay2017_MRIcelltracking(params_q_Treg_T_in_Tremblay2017_MRIcelltracking, inputs_q_Treg_T_in_Tremblay2017_MRIcelltracking)
    data["q_Treg_T_in_Tremblay2017_MRIcelltracking"].obs_median[1] ~ LogNormal(log(pred_q_Treg_T_in_Tremblay2017_MRIcelltracking), data["q_Treg_T_in_Tremblay2017_MRIcelltracking"].obs_sigma[1])

    # q_Treg_T_in_PDAC_Tang2014
    params_q_Treg_T_in_PDAC_Tang2014 = Dict("q_Treg_T_in" => q_Treg_T_in)
    inputs_q_Treg_T_in_PDAC_Tang2014 = data["q_Treg_T_in_PDAC_Tang2014"].inputs
    pred_q_Treg_T_in_PDAC_Tang2014 = compute_q_Treg_T_in_PDAC_Tang2014(params_q_Treg_T_in_PDAC_Tang2014, inputs_q_Treg_T_in_PDAC_Tang2014)
    data["q_Treg_T_in_PDAC_Tang2014"].obs_median[1] ~ LogNormal(log(pred_q_Treg_T_in_PDAC_Tang2014), data["q_Treg_T_in_PDAC_Tang2014"].obs_sigma[1])

    # q_Treg_T_in_extravasation_PDAC
    params_q_Treg_T_in_extravasation_PDAC = Dict("q_Treg_T_in" => q_Treg_T_in)
    inputs_q_Treg_T_in_extravasation_PDAC = data["q_Treg_T_in_extravasation_PDAC"].inputs
    pred_q_Treg_T_in_extravasation_PDAC = compute_q_Treg_T_in_extravasation_PDAC(params_q_Treg_T_in_extravasation_PDAC, inputs_q_Treg_T_in_extravasation_PDAC)
    data["q_Treg_T_in_extravasation_PDAC"].obs_median[1] ~ LogNormal(log(pred_q_Treg_T_in_extravasation_PDAC), data["q_Treg_T_in_extravasation_PDAC"].obs_sigma[1])

    # q_Treg_T_in_Jiang2014_Liyanage2002
    pred_q_Treg_T_in_Jiang2014_Liyanage2002 = simulate_q_Treg_T_in_Jiang2014_Liyanage2002(q_Treg_T_in, k_Treg_death)
    data["q_Treg_T_in_Jiang2014_Liyanage2002"].obs_median[1] ~ LogNormal(log(pred_q_Treg_T_in_Jiang2014_Liyanage2002), data["q_Treg_T_in_Jiang2014_Liyanage2002"].obs_sigma[1])

    return (N_IL2_CD4=N_IL2_CD4, N_IL2_CD8=N_IL2_CD8, k_C1_growth=k_C1_growth, k_CCL2_sec=k_CCL2_sec, k_CCL2_deg=k_CCL2_deg, k_M1_pol=k_M1_pol, k_M2_pol=k_M2_pol, k_MDSC_rec=k_MDSC_rec, k_MDSC_death=k_MDSC_death, k_Mac_rec=k_Mac_rec, k_Mac_death=k_Mac_death, k_apsc_death=k_apsc_death, k_psc_activation=k_psc_activation, n_CD8_clones=n_CD8_clones, q_CD8_T_in=q_CD8_T_in, k_CD8_death=k_CD8_death, cd8_exclusion_fraction=cd8_exclusion_fraction, q_Treg_T_in=q_Treg_T_in, k_Treg_death=k_Treg_death)
end

# ======================================================================
# RUN INFERENCE
# ======================================================================

model = joint_calibration(DATA)

println("=" ^ 60)
println("JOINT BAYESIAN CALIBRATION")
println("=" ^ 60)
println("\nTargets:")
println("  - N_IL2_CD4_division_destiny_Gett1998")
println("  - N_IL2_CD8_division_generations_castro2012")
println("  - k_C1_growth_pdac_human_vdt_ahn2017")
println("  - k_C1_growth_pdac_tumor_doubling_jang2015")
println("  - k_CCL2_sec_Fujita2010_PrSC")
println("  - k_CCL2_sec_Steube1999_proxy")
println("  - k_CCL2_sec_bcproxy_yoshimura2023")
println("  - k_CCL2_sec_psc_michalski2008")
println("  - k_CCL2_sec_pdac_plasma_Nixon2013")
println("  - k_M1_pol_Watkins2007_IL12_TAM_reprogramming")
println("  - k_M1_pol_repolarization_horhold2020")
println("  - k_M1_pol_rp182_m2_to_m1_repolarization")
println("  - k_M1_pol_pdac_cd86_cd163_gu2023")
println("  - k_M1_pol_steady_state_ratio_DLBCL2021")
println("  - k_M1_pol_pdac_m1m2ratio_DeSimoni2023")
println("  - k_M1_pol_tam_ratio_herwig2013")
println("  - k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015")
println("  - k_MDSC_rec_oscc_ccl2_oo2022")
println("  - k_MDSC_rec_PDAC_Porembka2012")
println("  - k_MDSC_rec_panc02_spleenexpansion_ghansah2013")
println("  - k_MDSC_rec_pdac_trovato2019")
println("  - k_MDSC_rec_panc02_tnfr1_chopra2013")
println("  - k_Mac_rec_PDAC_M1_recruitment_Gu2023")
println("  - k_Mac_rec_PDAC_TAM_recruitment_Chen2015")
println("  - k_Mac_rec_humanPDAC_CD40_2021")
println("  - k_apsc_death_melatoninPSC_Estaras2021")
println("  - k_apsc_death_RA_Xiao2015")
println("  - k_apsc_death_hsc_apoptosis_issa2001")
println("  - k_psc_activation_apte1998")
println("  - n_CD8_clones_Meng2023_PDAC")
println("  - q_CD8_T_in_extravasation_boissonnas2007")
println("  - q_CD8_T_in_yorty2007_sv11_brain_tumor")
println("  - q_CD8_T_in_PDAC_CD8density_ModPathol2019")
println("  - q_Treg_T_in_Tremblay2017_MRIcelltracking")
println("  - q_Treg_T_in_PDAC_Tang2014")
println("  - q_Treg_T_in_extravasation_PDAC")
println("  - q_Treg_T_in_Jiang2014_Liyanage2002")
println("\nParameters to estimate:")
println("  N_IL2_CD4 (dimensionless) - constrained by: N_IL2_CD4_division_destiny_Gett1998")
println("  N_IL2_CD8 (dimensionless) - constrained by: N_IL2_CD8_division_generations_castro2012")
println("  k_C1_growth (1/day) - constrained by: k_C1_growth_pdac_human_vdt_ahn2017, k_C1_growth_pdac_tumor_doubling_jang2015")
println("  k_CCL2_sec (nanomole/cell/day) - constrained by: k_CCL2_sec_Fujita2010_PrSC, k_CCL2_sec_Steube1999_proxy, k_CCL2_sec_bcproxy_yoshimura2023, k_CCL2_sec_psc_michalski2008, k_CCL2_sec_pdac_plasma_Nixon2013")
println("  k_CCL2_deg (1 / day) - constrained by: k_CCL2_sec_pdac_plasma_Nixon2013")
println("  k_M1_pol (1/day) - constrained by: k_M1_pol_Watkins2007_IL12_TAM_reprogramming, k_M1_pol_repolarization_horhold2020, k_M1_pol_rp182_m2_to_m1_repolarization, k_M1_pol_pdac_cd86_cd163_gu2023, k_M1_pol_steady_state_ratio_DLBCL2021, k_M1_pol_pdac_m1m2ratio_DeSimoni2023, k_M1_pol_tam_ratio_herwig2013, k_Mac_rec_humanPDAC_CD40_2021")
println("  k_M2_pol (1/day) - constrained by: k_M1_pol_pdac_cd86_cd163_gu2023, k_M1_pol_steady_state_ratio_DLBCL2021, k_M1_pol_pdac_m1m2ratio_DeSimoni2023, k_M1_pol_tam_ratio_herwig2013, k_Mac_rec_humanPDAC_CD40_2021")
println("  k_MDSC_rec (cell/(milliliter*day)) - constrained by: k_MDSC_rec_recruitment_pericyte_MDSC_Hong2015, k_MDSC_rec_oscc_ccl2_oo2022, k_MDSC_rec_PDAC_Porembka2012, k_MDSC_rec_panc02_spleenexpansion_ghansah2013, k_MDSC_rec_pdac_trovato2019, k_MDSC_rec_panc02_tnfr1_chopra2013")
println("  k_MDSC_death (1/day) - constrained by: k_MDSC_rec_PDAC_Porembka2012, k_MDSC_rec_pdac_trovato2019, k_MDSC_rec_panc02_tnfr1_chopra2013")
println("  k_Mac_rec (cell/(milliliter*day)) - constrained by: k_Mac_rec_PDAC_M1_recruitment_Gu2023, k_Mac_rec_PDAC_TAM_recruitment_Chen2015")
println("  k_Mac_death (1/day) - constrained by: k_Mac_rec_PDAC_M1_recruitment_Gu2023, k_Mac_rec_PDAC_TAM_recruitment_Chen2015")
println("  k_apsc_death (1/day) - constrained by: k_apsc_death_melatoninPSC_Estaras2021, k_apsc_death_RA_Xiao2015, k_apsc_death_hsc_apoptosis_issa2001")
println("  k_psc_activation (1/day) - constrained by: k_psc_activation_apte1998")
println("  n_CD8_clones (dimensionless) - constrained by: n_CD8_clones_Meng2023_PDAC")
println("  q_CD8_T_in (1 / (centimeter**3 * minute)) - constrained by: q_CD8_T_in_extravasation_boissonnas2007, q_CD8_T_in_yorty2007_sv11_brain_tumor, q_CD8_T_in_PDAC_CD8density_ModPathol2019")
println("  k_CD8_death (1/day) - constrained by: q_CD8_T_in_PDAC_CD8density_ModPathol2019")
println("  cd8_exclusion_fraction (dimensionless) - constrained by: q_CD8_T_in_PDAC_CD8density_ModPathol2019")
println("  q_Treg_T_in (1/(centimeter^3*minute)) - constrained by: q_Treg_T_in_Tremblay2017_MRIcelltracking, q_Treg_T_in_PDAC_Tang2014, q_Treg_T_in_extravasation_PDAC, q_Treg_T_in_Jiang2014_Liyanage2002")
println("  k_Treg_death (1/day) - constrained by: q_Treg_T_in_Jiang2014_Liyanage2002")

println("\nSampling with NUTS...")
chain = sample(model, NUTS(0.65), MCMCThreads(), 1000, 4; progress=true)

println("\n" * "=" ^ 60)
println("POSTERIOR SUMMARY")
println("=" ^ 60)
display(chain)

# Convergence diagnostics
println("\nConvergence diagnostics:")
params = [:N_IL2_CD4, :N_IL2_CD8, :k_C1_growth, :k_CCL2_sec, :k_CCL2_deg, :k_M1_pol, :k_M2_pol, :k_MDSC_rec, :k_MDSC_death, :k_Mac_rec, :k_Mac_death, :k_apsc_death, :k_psc_activation, :n_CD8_clones, :q_CD8_T_in, :k_CD8_death, :cd8_exclusion_fraction, :q_Treg_T_in, :k_Treg_death]
for p in params
    rhat_val = rhat(chain[p])[1]
    ess_val = ess(chain[p])[1]
    status = rhat_val < 1.01 ? "✓" : "⚠"
    println("  $p: R-hat=$(round(rhat_val, digits=3)) $status, ESS=$(round(ess_val, digits=0))")
end

println("\n" * "=" ^ 60)
println("POSTERIOR MEDIANS AND 90% CI")
println("=" ^ 60)
let samples = chain[:N_IL2_CD4][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  N_IL2_CD4: $med (dimensionless)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:N_IL2_CD8][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  N_IL2_CD8: $med (dimensionless)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_C1_growth][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_C1_growth: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_CCL2_sec][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_CCL2_sec: $med (nanomole/cell/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_CCL2_deg][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_CCL2_deg: $med (1 / day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_M1_pol][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_M1_pol: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_M2_pol][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_M2_pol: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_MDSC_rec][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_MDSC_rec: $med (cell/(milliliter*day))  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_MDSC_death][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_MDSC_death: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_Mac_rec][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_Mac_rec: $med (cell/(milliliter*day))  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_Mac_death][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_Mac_death: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_apsc_death][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_apsc_death: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_psc_activation][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_psc_activation: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:n_CD8_clones][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  n_CD8_clones: $med (dimensionless)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:q_CD8_T_in][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  q_CD8_T_in: $med (1 / (centimeter**3 * minute))  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_CD8_death][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_CD8_death: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:cd8_exclusion_fraction][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  cd8_exclusion_fraction: $med (dimensionless)  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:q_Treg_T_in][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  q_Treg_T_in: $med (1/(centimeter^3*minute))  [90% CI: $ci_lo - $ci_hi]")
end
let samples = chain[:k_Treg_death][:]
    med = round(median(samples), sigdigits=4)
    ci_lo = round(quantile(samples, 0.05), sigdigits=4)
    ci_hi = round(quantile(samples, 0.95), sigdigits=4)
    println("  k_Treg_death: $med (1/day)  [90% CI: $ci_lo - $ci_hi]")
end

# Plot marginal posteriors with priors
println("\nPlotting marginal posteriors...")

param_names = [:N_IL2_CD4, :N_IL2_CD8, :k_C1_growth, :k_CCL2_sec, :k_CCL2_deg, :k_M1_pol, :k_M2_pol, :k_MDSC_rec, :k_MDSC_death, :k_Mac_rec, :k_Mac_death, :k_apsc_death, :k_psc_activation, :n_CD8_clones, :q_CD8_T_in, :k_CD8_death, :cd8_exclusion_fraction, :q_Treg_T_in, :k_Treg_death]
param_labels = ["N_IL2_CD4", "N_IL2_CD8", "k_C1_growth", "k_CCL2_sec", "k_CCL2_deg", "k_M1_pol", "k_M2_pol", "k_MDSC_rec", "k_MDSC_death", "k_Mac_rec", "k_Mac_death", "k_apsc_death", "k_psc_activation", "n_CD8_clones", "q_CD8_T_in", "k_CD8_death", "cd8_exclusion_fraction", "q_Treg_T_in", "k_Treg_death"]

priors = Dict(
    :N_IL2_CD4 => Normal(8.0, 2.0),
    :N_IL2_CD8 => Normal(5.0, 2.0),
    :k_C1_growth => LogNormal(-5.0, 1.0),
    :k_CCL2_sec => LogNormal(-20.64, 2.5),
    :k_CCL2_deg => LogNormal(1.94, 0.3),
    :k_M1_pol => LogNormal(0.0, 3.4),
    :k_M2_pol => LogNormal(0.0, 3.4),
    :k_MDSC_rec => LogNormal(17.44, 2.5),
    :k_MDSC_death => LogNormal(0.0, 1.5),
    :k_Mac_rec => LogNormal(13.89, 1.5),
    :k_Mac_death => LogNormal(-3.91, 1.0),
    :k_apsc_death => LogNormal(-2.65, 1.7),
    :k_psc_activation => LogNormal(-0.693, 1.0),
    :n_CD8_clones => LogNormal(2.3, 1.0),
    :q_CD8_T_in => LogNormal(-8.0, 3.4),
    :k_CD8_death => LogNormal(0.0, 1.0),
    :cd8_exclusion_fraction => Uniform(0.7, 0.99),
    :q_Treg_T_in => LogNormal(-7.0, 2.0),
    :k_Treg_death => LogNormal(-2.3, 1.0)
)

plots = []
for (i, pname) in enumerate(param_names)
    samples = vec(chain[pname])
    med = median(samples)
    ci_lo = quantile(samples, 0.05)
    ci_hi = quantile(samples, 0.95)

    # X range based on posterior samples
    xmin, xmax = quantile(samples, 0.001), quantile(samples, 0.999)
    xrange = range(xmin, xmax, length=200)

    # Prior density
    prior_dist = priors[pname]
    prior_pdf = pdf.(prior_dist, xrange)

    # Start with prior (gray, underneath)
    plt = plot(xrange, prior_pdf;
        fill=true, fillalpha=0.2, color=:gray, linewidth=1, linecolor=:gray,
        xlabel=param_labels[i], ylabel="",
        label="Prior", legend=false, grid=false, framestyle=:box,
        xrotation=45)

    # Overlay posterior density
    density!(plt, samples;
        fill=true, fillalpha=0.4, color=:steelblue, linewidth=2,
        label="Posterior")

    # Add median and CI lines
    vline!(plt, [med]; color=:red, linewidth=2, linestyle=:solid, label="")
    vline!(plt, [ci_lo, ci_hi]; color=:red, linewidth=1, linestyle=:dash, label="")

    push!(plots, plt)
end

p = plot(plots...; layout=(7, 3), size=(1200, 1000), margin=8mm)
savefig(p, "posterior_marginals.png")
println("Saved: posterior_marginals.png")

# ======================================================================
# SAVE RESULTS TO JSON FOR AUTOMATED PROCESSING
# ======================================================================
using JSON

results = Dict(
    "n_chains" => 4,
    "n_samples" => 1000,
    "parameters" => Dict()
)

# Store raw samples for plotting
posterior_samples = Dict{String, Vector{Float64}}()

for pname in param_names
    samples = vec(chain[pname])
    rhat_val = rhat(chain[pname])[1]
    ess_bulk = ess(chain[pname])[1]
    ess_tail = ess(chain[pname]; kind=:tail)[1]

    # Store raw samples
    posterior_samples[string(pname)] = samples

    results["parameters"][string(pname)] = Dict(
        "median" => median(samples),
        "mean" => mean(samples),
        "std" => std(samples),
        "ci_05" => quantile(samples, 0.05),
        "ci_95" => quantile(samples, 0.95),
        "ci_025" => quantile(samples, 0.025),
        "ci_975" => quantile(samples, 0.975),
        "rhat" => rhat_val,
        "ess_bulk" => ess_bulk,
        "ess_tail" => ess_tail
    )
end

open("inference_results.json", "w") do f
    JSON.print(f, results, 2)
end
println("\nSaved: inference_results.json")

# Save raw posterior samples for plotting
open("posterior_samples.json", "w") do f
    JSON.print(f, posterior_samples, 2)
end
println("Saved: posterior_samples.json")
